# -*- coding: utf-8 -*-
"""PreProcessing_data_reference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHsK4YbfneM3aHRVImAkTUUj4NCtncus
"""

import pandas as pd
import numpy as np
import os

from google.colab import drive
drive.mount('/content/drive')

input_folder = "/content/drive/MyDrive/TFG/data/reference"
output_folder = "/content/drive/MyDrive/TFG/data_processed/reference_clusters"

input_folder = "/content/drive/MyDrive/TFG/data/reference"
output_folder = "/content/drive/MyDrive/TFG/data_processed/reference_clusters"

os.makedirs(output_folder, exist_ok=True)

centers = np.array([
[-3,-3],[-3,-1],[-3,1],[-3,3],
[-1,-3],[-1,-1],[-1,1],[-1,3],
[1,-3],[1,-1],[1,1],[1,3],
[3,-3],[3,-1],[3,1],[3,3]
])

for file in os.listdir(input_folder):

    if not file.endswith(".csv"):
        continue

    print("Processing:", file)

    path = os.path.join(input_folder, file)
    df = pd.read_csv(path)

    Q = []
    X_norm = []
    Y_norm = []

    for _,row in df.iterrows():

        point = np.array([row["Real"], row["Imag"]])

        distances = np.linalg.norm(centers - point, axis=1)
        q = np.argmin(distances)

        cx,cy = centers[q]

        Q.append(q)
        X_norm.append(row["Real"] - cx)
        Y_norm.append(row["Imag"] - cy)

    df["Q"] = Q
    df["X_norm"] = X_norm
    df["Y_norm"] = Y_norm

    output_path = os.path.join(output_folder, file)
    df.to_csv(output_path, index=False)

print("Done!")