# -*- coding: utf-8 -*-
"""WGAN_model2_git.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ls-Zz6A0uqeXLCmeF69bFJS_cA9s5_jE
"""

import os
import json
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
from sklearn.metrics import (
    precision_recall_curve, roc_curve, roc_auc_score,
    f1_score, precision_score, recall_score, average_precision_score,
)
from google.colab import drive

drive.mount('/content/drive')

SAVE_DIR = "/content/drive/MyDrive/TFG/results/model2_wgan"
MODELS_DIR = os.path.join(SAVE_DIR, "models")
FIGURES_DIR = os.path.join(SAVE_DIR, "figures")
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(FIGURES_DIR, exist_ok=True)

REFERENCE_FOLDER = "/content/drive/MyDrive/TFG/data_processed/reference_clusters"

print(f"Save dir: {SAVE_DIR}")
print(f"Reference data: {REFERENCE_FOLDER}")

SEED = 42

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

set_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")
print(f"Seed: {SEED}")

# Hiperparámetros
LATENT_DIM = 128
RESOLUTION = 96
BATCH_SIZE = 64
NUM_EPOCHS = 200
LAMBDA_GP = 10.0
N_CRITIC = 5
MIN_POINTS = 100
VALUE_RANGE = (-4.5, 4.5)
THRESHOLD_PERCENTILE = 5

TEST_FRACTION = 0.2
SPLIT_SEED = 42

def create_histogram(x, y, resolution=96, value_range=(-4.5, 4.5)):

    H, _, _ = np.histogram2d(
        x, y,
        bins=resolution,
        range=[[value_range[0], value_range[1]],
               [value_range[0], value_range[1]]],
    )
    if H.max() > 0:
        H = H / H.max()
    H = H * 2 - 1
    return H


def list_csv_files(folder):
    return sorted([f for f in os.listdir(folder) if f.endswith(".csv")])


def enumerate_sample_keys(folder, min_points=100):

    keys = []
    files = list_csv_files(folder)
    for file in files:
        path = os.path.join(folder, file)
        sample_ids_col = pd.read_csv(path, usecols=["Sample_Id"])["Sample_Id"]
        counts = sample_ids_col.value_counts()
        for sid, count in counts.items():
            if count >= min_points:
                keys.append((file, int(sid)))
    return keys


def compute_train_test_split(folder, test_fraction=0.2, seed=42, min_points=100):

    keys = enumerate_sample_keys(folder, min_points=min_points)

    # Agrupar claves por archivo (cada archivo = una distancia)
    keys_by_file = {}
    for key in keys:
        file = key[0]
        keys_by_file.setdefault(file, []).append(key)

    rng = np.random.default_rng(seed)
    train_keys, test_keys = set(), set()
    test_per_file = {}
    for file in sorted(keys_by_file.keys()):     # sort para determinismo
        file_keys = keys_by_file[file]
        indices = np.arange(len(file_keys))
        rng.shuffle(indices)
        n_test = int(round(len(file_keys) * test_fraction))
        for rank, idx in enumerate(indices):
            if rank < n_test:
                test_keys.add(file_keys[idx])
            else:
                train_keys.add(file_keys[idx])
        test_per_file[file] = n_test


    print(f"Split  por archivo (distancia):")
    print(f"  Archivos: {len(keys_by_file)} | "
          f"Total samples válidos: {len(keys)}")
    print(f"  Train: {len(train_keys)} samples | Test: {len(test_keys)} samples")
    print(f"  Test por archivo: {sorted(set(test_per_file.values()))} "
          f"(seed={seed}, test_fraction={test_fraction})")
    return train_keys, test_keys


class IQHistogramDataset(Dataset):

    def __init__(self, files, folder, resolution=96, value_range=(-4.5, 4.5),
                 min_points=100, allowed_keys=None):
        self.data = []
        self.metadata = []

        for file in files:
            path = os.path.join(folder, file)
            df = pd.read_csv(path)
            for sample_id in df["Sample_Id"].unique():
                key = (file, int(sample_id))
                if allowed_keys is not None and key not in allowed_keys:
                    continue
                df_sample = df[df["Sample_Id"] == sample_id]
                x = df_sample["Real"].values
                y = df_sample["Imag"].values
                if len(x) < min_points:
                    continue
                hist = create_histogram(x, y, resolution=resolution,
                                        value_range=value_range)
                self.data.append(hist)
                self.metadata.append({
                    "file": file,
                    "sample_id": int(sample_id),
                    "n_points": int(len(x)),
                })

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img = torch.tensor(self.data[idx], dtype=torch.float32).unsqueeze(0)
        return img


def build_dataloader(folder, batch_size=64, shuffle=True, resolution=96,
                     value_range=(-4.5, 4.5), min_points=100,
                     allowed_keys=None):
    files = list_csv_files(folder)
    dataset = IQHistogramDataset(
        files, folder,
        resolution=resolution,
        value_range=value_range,
        min_points=min_points,
        allowed_keys=allowed_keys,
    )
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)
    label = "all"
    if allowed_keys is not None:
        label = f"split-{len(allowed_keys)}-keys"
    print(f"Loaded {len(files)} files from {folder} ({label}) -> {len(dataset)} samples")
    return dataset, loader

def generator_block(in_channels, out_channels):
    #Upsample + Conv2d en lugar de ConvTranspose2d para evitar ruido ajedrezz
    return nn.Sequential(
        nn.Upsample(scale_factor=2, mode="nearest"),
        nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=1, padding=1),
        nn.BatchNorm2d(out_channels),
        nn.ReLU(inplace=True),
        nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1),
        nn.BatchNorm2d(out_channels),
        nn.ReLU(inplace=True),
    )


class Generator(nn.Module):

    def __init__(self, latent_dim=128, base_channels=64):
        super().__init__()
        self.init_size = 6
        c_init = base_channels * 8

        self.fc = nn.Linear(latent_dim, c_init * self.init_size * self.init_size)
        self.stem = nn.Sequential(
            nn.Conv2d(c_init, c_init, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(c_init),
            nn.ReLU(inplace=True),
        )

        self.block1 = generator_block(c_init, base_channels * 4)            # 6 -->12,  256 canal
        self.block2 = generator_block(base_channels * 4, base_channels * 2) # 12-->24, 128 can
        self.block3 = generator_block(base_channels * 2, base_channels)     # 24-->48,  64 can
        self.block4 = generator_block(base_channels, base_channels)         # 48-->96,  64 can

        self.to_image = nn.Sequential(
            nn.Conv2d(base_channels, 1, kernel_size=3, stride=1, padding=1),
            nn.Tanh(),
        )

    def forward(self, z):
        x = self.fc(z)
        x = x.view(z.size(0), -1, self.init_size, self.init_size)
        x = self.stem(x)
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        x = self.block4(x)
        return self.to_image(x)

def snconv(in_channels, out_channels, kernel_size, stride, padding):
    #spectral norm
    return nn.utils.spectral_norm(
        nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding)
    )


class Critic(nn.Module):

    def __init__(self, base_channels=64):
        super().__init__()
        layers = [
            # 96 -> 48
            snconv(1, base_channels, 4, 2, 1),
            nn.LeakyReLU(0.2, inplace=True),
            snconv(base_channels, base_channels, 3, 1, 1),
            nn.LeakyReLU(0.2, inplace=True),

            # 48 -> 24
            snconv(base_channels, base_channels * 2, 4, 2, 1),
            nn.LeakyReLU(0.2, inplace=True),
            snconv(base_channels * 2, base_channels * 2, 3, 1, 1),
            nn.LeakyReLU(0.2, inplace=True),

            # 24 -> 12
            snconv(base_channels * 2, base_channels * 4, 4, 2, 1),
            nn.LeakyReLU(0.2, inplace=True),
            snconv(base_channels * 4, base_channels * 4, 3, 1, 1),
            nn.LeakyReLU(0.2, inplace=True),

            # 12 -> 6
            snconv(base_channels * 4, base_channels * 8, 4, 2, 1),
            nn.LeakyReLU(0.2, inplace=True),
            snconv(base_channels * 8, base_channels * 8, 3, 1, 1),
            nn.LeakyReLU(0.2, inplace=True),

            # 6 -> 1
            snconv(base_channels * 8, 1, 6, 1, 0),
            nn.Flatten(),
        ]
        self.model = nn.Sequential(*layers)

    def forward(self, x):
        return self.model(x)

def histogram_to_iq_points(hist, num_points=2048, value_range=(-4.5, 4.5)):
    #Muestrea num_points puntos IQ a partir de un histograma
    if hist.ndim == 3:
        hist = hist.squeeze()
    hist = np.asarray(hist, dtype=np.float32)
    hist = hist - hist.min()
    total = hist.sum()
    if total <= 0:
        flat_prob = np.full(hist.size, 1.0 / hist.size, dtype=np.float32)
    else:
        flat_prob = (hist / total).flatten()

    sampled_idx = np.random.choice(len(flat_prob), size=num_points, p=flat_prob)
    rows, cols = np.unravel_index(sampled_idx, hist.shape)
    min_val, max_val = value_range
    x = min_val + (rows / hist.shape[0]) * (max_val - min_val)
    y = min_val + (cols / hist.shape[1]) * (max_val - min_val)
    pixel_size_x = (max_val - min_val) / hist.shape[0]
    pixel_size_y = (max_val - min_val) / hist.shape[1]
    x += np.random.uniform(-pixel_size_x / 2, pixel_size_x / 2, size=num_points)
    y += np.random.uniform(-pixel_size_y / 2, pixel_size_y / 2, size=num_points)
    return x, y

#Conversión inversa: nube de puntos IQ a histograma normalizado [-1, 1].
def iq_to_histogram(x, y, resolution=96, value_range=(-4.5, 4.5)):

    return create_histogram(x, y, resolution=resolution, value_range=value_range)

def gradient_penalty(critic, real, fake, device):
#funcion objetivo
    batch_size = real.size(0)
    epsilon = torch.rand(batch_size, 1, 1, 1, device=device)
    interpolated = epsilon * real + (1 - epsilon) * fake
    interpolated.requires_grad_(True)
    d_interpolated = critic(interpolated)
    gradients = torch.autograd.grad(
        outputs=d_interpolated,
        inputs=interpolated,
        grad_outputs=torch.ones_like(d_interpolated),
        create_graph=True,
        retain_graph=True,
    )[0]
    gradients = gradients.view(batch_size, -1)
    gp = ((gradients.norm(2, dim=1) - 1) ** 2).mean()
    return gp


def train_wgan_gp(generator, critic, dataloader, optimizer_G, optimizer_C,
                  num_epochs, latent_dim, device,
                  lambda_gp=10.0, n_critic=5,
                  collapse_patience=20, collapse_gap_eps=1e-4):

    history = {
        "loss_G": [], "loss_D": [],
        "real_score": [], "fake_score": [], "critic_gap": [],
    }
    collapse_counter = 0

    generator.train()
    critic.train()

    print(f"WGAN-GP training: epochs={num_epochs}, n_critic={n_critic}, "
          f"lambda_gp={lambda_gp}, device={device}")

    for epoch in range(num_epochs):
        epoch_g_losses = []
        epoch_d_losses = []
        epoch_real_scores = []
        epoch_fake_scores = []

        for batch_idx, real_imgs in enumerate(dataloader):
            real_imgs = real_imgs.to(device)
            batch_size = real_imgs.size(0)


           #act. critico
            z = torch.randn(batch_size, latent_dim, device=device)
            fake_imgs = generator(z).detach()

            real_validity = critic(real_imgs)
            fake_validity = critic(fake_imgs)
            gp = gradient_penalty(critic, real_imgs, fake_imgs, device)
            loss_D = -(real_validity.mean() - fake_validity.mean()) + lambda_gp * gp

            optimizer_C.zero_grad(set_to_none=True)
            loss_D.backward()
            optimizer_C.step()

            epoch_d_losses.append(loss_D.item())
            epoch_real_scores.append(real_validity.mean().item())
            epoch_fake_scores.append(fake_validity.mean().item())

            # act. generador cada n_critic veces
            if batch_idx % n_critic == 0:
                z = torch.randn(batch_size, latent_dim, device=device)
                fake_imgs = generator(z)
                loss_G = -critic(fake_imgs).mean()

                optimizer_G.zero_grad(set_to_none=True)
                loss_G.backward()
                optimizer_G.step()
                epoch_g_losses.append(loss_G.item())

        epoch_g_loss = float(np.mean(epoch_g_losses)) if epoch_g_losses else float("nan")
        epoch_d_loss = float(np.mean(epoch_d_losses)) if epoch_d_losses else float("nan")
        epoch_real_score = float(np.mean(epoch_real_scores)) if epoch_real_scores else float("nan")
        epoch_fake_score = float(np.mean(epoch_fake_scores)) if epoch_fake_scores else float("nan")
        critic_gap = epoch_real_score - epoch_fake_score

        history["loss_G"].append(epoch_g_loss)
        history["loss_D"].append(epoch_d_loss)
        history["real_score"].append(epoch_real_score)
        history["fake_score"].append(epoch_fake_score)
        history["critic_gap"].append(critic_gap)

        print(f"Epoch [{epoch+1}/{num_epochs}] | "
              f"Loss D: {epoch_d_loss:.4f} | Loss G: {epoch_g_loss:.4f} | "
              f"Real: {epoch_real_score:.4f} | Fake: {epoch_fake_score:.4f} | "
              f"Gap (W est.): {critic_gap:.4f}")

        if not np.isfinite(epoch_d_loss) or not np.isfinite(epoch_g_loss):
            print("Stopping: pérdidas no finitas.")
            break

        if abs(critic_gap) < collapse_gap_eps:
            collapse_counter += 1
        else:
            collapse_counter = 0

        if collapse_counter >= collapse_patience:
            print(f"Stopping: crítico colapsado (gap≈0 durante {collapse_patience} epochs).")
            break

    return history

def scores_from_loader(critic, dataloader, device):
    scores = []
    critic.eval()
    with torch.no_grad():
        for imgs in dataloader:
            imgs = imgs.to(device)
            out = critic(imgs).cpu().numpy().flatten()
            scores.extend(out)
    return np.array(scores)


def scores_from_generator_components(generator, critic, latent_dim,
                                     n_samples, device, batch_size=64):
    scores = []
    generator.eval()
    critic.eval()
    n_done = 0
    with torch.no_grad():
        while n_done < n_samples:
            b = min(batch_size, n_samples - n_done)
            z = torch.randn(b, latent_dim, device=device)
            fakes = generator(z)
            s = critic(fakes).cpu().numpy().flatten()
            scores.extend(s)
            n_done += b
    return np.array(scores)


def evaluate_components(generator, critic, reference_loader, latent_dim,
                        n_samples, device):
    print("  Computing scores on reference (loader a critic)...")
    scores_real = scores_from_loader(critic, reference_loader, device)
    print("  Generating and scoring synthetic samples (z --> G --> critic)...")
    scores_generated = scores_from_generator_components(
        generator, critic, latent_dim, n_samples, device
    )
    return scores_real, scores_generated

def classification_metrics(y_true, y_score, threshold):
    y_pred = (y_score >= threshold).astype(int)
    tp = int(np.sum((y_true == 1) & (y_pred == 1)))
    fp = int(np.sum((y_true == 0) & (y_pred == 1)))
    tn = int(np.sum((y_true == 0) & (y_pred == 0)))
    fn = int(np.sum((y_true == 1) & (y_pred == 0)))
    rec = float(recall_score(y_true, y_pred, zero_division=0))
    return {
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": rec,
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
        "fpr": float(fp / (fp + tn + 1e-12)),
        "detection_rate": rec,
        "tp": tp, "fp": fp, "tn": tn, "fn": fn,
    }


def best_f1_from_pr(y_true, y_score):
    precision, recall, thresholds = precision_recall_curve(y_true, y_score)
    if len(thresholds) == 0:
        return float("nan"), float("nan"), float("nan"), float("nan")
    f1_scores = (2 * precision[:-1] * recall[:-1]) / (precision[:-1] + recall[:-1] + 1e-12)
    best_idx = int(np.argmax(f1_scores))
    return (float(thresholds[best_idx]),
            float(precision[best_idx]),
            float(recall[best_idx]),
            float(f1_scores[best_idx]))


def compute_metrics(scores_real, scores_generated, threshold_percentile=5):
    #anomaly = -critic.
    anomaly_real = -np.asarray(scores_real)
    anomaly_generated = -np.asarray(scores_generated)

    y_true = np.concatenate([np.zeros_like(anomaly_real),
                             np.ones_like(anomaly_generated)])
    y_score = np.concatenate([anomaly_real, anomaly_generated])

    roc_fpr, roc_tpr, _ = roc_curve(y_true, y_score)
    roc_auc = float(roc_auc_score(y_true, y_score))
    pr_precision, pr_recall, _ = precision_recall_curve(y_true, y_score)
    pr_auc = float(average_precision_score(y_true, y_score))

    mean_r = float(np.mean(anomaly_real))
    std_r = float(np.std(anomaly_real))
    threshold_3sigma = mean_r + 3.0 * std_r
    threshold_p5 = float(np.percentile(anomaly_real, 100 - threshold_percentile))

    best_th, best_p, best_r, best_f1 = best_f1_from_pr(y_true, y_score)

    metrics_3sigma = classification_metrics(y_true, y_score, threshold_3sigma)
    metrics_p5 = classification_metrics(y_true, y_score, threshold_p5)
    metrics_best = classification_metrics(y_true, y_score, best_th)

    return {
        # Arrays
        "anomaly_real": anomaly_real,
        "anomaly_generated": anomaly_generated,
        "y_true": y_true, "y_score": y_score,
        "roc_fpr": roc_fpr, "roc_tpr": roc_tpr,
        "pr_precision": pr_precision, "pr_recall": pr_recall,
        # Escalares
        "roc_auc": roc_auc, "pr_auc": pr_auc,
        "mean_real": mean_r, "std_real": std_r,
        "mean_generated": float(np.mean(anomaly_generated)),
        "std_generated": float(np.std(anomaly_generated)),
        "threshold_p5": threshold_p5,
        "threshold_3sigma": threshold_3sigma,
        "best_threshold": float(best_th),
        "best_precision": float(best_p),
        "best_recall": float(best_r),
        "best_f1": float(best_f1),
        "metrics_p5": metrics_p5,
        "metrics_3sigma": metrics_3sigma,
        "metrics_best": metrics_best,
    }

#para guardar en JSON
def serializable_subset(results):
    keys = ["roc_auc", "pr_auc",
            "mean_real", "std_real", "mean_generated", "std_generated",
            "threshold_p5", "threshold_3sigma",
            "best_threshold", "best_precision", "best_recall", "best_f1",
            "metrics_p5", "metrics_3sigma", "metrics_best"]
    return {k: results[k] for k in keys}


def build_metrics_text(results, header=""):
    lines = []
    if header:
        lines.append(header)
        lines.append("-" * len(header))
    lines.extend([
        f"ROC AUC: {results['roc_auc']:.4f}",
        f"PR AUC: {results['pr_auc']:.4f}",
        f"Mean anomaly score (reference):  {results['mean_real']:.4f} (std {results['std_real']:.4f})",
        f"Mean anomaly score (generated):  {results['mean_generated']:.4f} (std {results['std_generated']:.4f})",
        "",
        f"Best F1: {results['best_f1']:.4f} @ threshold = {results['best_threshold']:.4f}",
        f"  Precision: {results['metrics_best']['precision']:.4f} | "
        f"Recall: {results['metrics_best']['recall']:.4f}",
        "",
        f"Threshold percentil 5 (sobre reference): {results['threshold_p5']:.4f}",
        f"  Detection rate: {results['metrics_p5']['detection_rate']:.4f} | "
        f"FPR: {results['metrics_p5']['fpr']:.4f}",
        f"Threshold μ+3σ (sobre reference): {results['threshold_3sigma']:.4f}",
        f"  Detection rate: {results['metrics_3sigma']['detection_rate']:.4f} | "
        f"FPR: {results['metrics_3sigma']['fpr']:.4f}",
    ])
    return "\n".join(lines)

def save_figure(fig, path):
    fig.savefig(path, dpi=200, bbox_inches="tight")
    plt.close(fig)


def plot_training_losses(history, save_path):
#perdidas WGAN
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(history["loss_D"], label="Critic loss  (-(W est.) + λ·GP)",
            color="tab:blue", alpha=0.85)
    ax.plot(history["loss_G"], label="Generator loss  (-C(G(z)))",
            color="tab:orange", alpha=0.85)
    ax.axhline(0, color="black", linestyle=":", alpha=0.4)
    ax.set_title("Evolución de losses durante entrenamiento (WGAN-GP)")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss")
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend()
    save_figure(fig, save_path)


def plot_score_evolution(history, save_path):

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(history["real_score"], label="Critic(real)", color="tab:green")
    ax.plot(history["fake_score"], label="Critic(fake)", color="tab:red")
    ax.plot(history["critic_gap"], label="W estimate (real - fake)",
            color="tab:purple", linestyle="--")
    ax.axhline(0, color="black", linestyle=":", alpha=0.4)
    ax.set_title("Evolución de scores del crítico (Wasserstein estimate)")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Score")
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend()
    save_figure(fig, save_path)


def plot_samples_grid(images, save_path, title, value_range=(-4.5, 4.5), n_show=4):
    #Plot de N muestras
    n_show = min(n_show, len(images))
    if n_show == 4:
        cols, panel_size = 2, 5
    elif n_show == 10:
        cols, panel_size = 5, 3
    else:
        cols = int(np.ceil(np.sqrt(n_show)))
        panel_size = 4
    rows = (n_show + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(panel_size * cols, panel_size * rows))
    if rows == 1 and cols == 1:
        axes = np.array([[axes]])
    elif rows == 1:
        axes = axes.reshape(1, -1)
    elif cols == 1:
        axes = axes.reshape(-1, 1)
    extent = [value_range[0], value_range[1], value_range[0], value_range[1]]
    for i, ax in enumerate(axes.flat):
        if i < n_show:
            ax.imshow(images[i].T, cmap="viridis", origin="lower",
                      extent=extent, aspect="equal")
            ax.set_title(f"#{i+1}", fontsize=12)
            ax.set_xlabel("Real")
            ax.set_ylabel("Imag")
            ax.tick_params(labelsize=9)
        else:
            ax.axis("off")
    fig.suptitle(title, fontsize=14)
    fig.tight_layout()
    save_figure(fig, save_path)


def plot_samples_reference(reference_loader, save_path, value_range, n_show=4):
    imgs = next(iter(reference_loader))[:n_show, 0].cpu().numpy()
    plot_samples_grid(imgs, save_path,
                      "Muestras reference (histogramas 96×96, constelación completa)",
                      value_range=value_range, n_show=n_show)


def plot_samples_generated(generator, latent_dim, device, save_path,
                           value_range, n_show=4):
    generator.eval()
    with torch.no_grad():
        z = torch.randn(n_show, latent_dim, device=device)
        imgs = generator(z).cpu().numpy()[:, 0]
    plot_samples_grid(imgs, save_path,
                      "Muestras generated (histogramas 96×96)",
                      value_range=value_range, n_show=n_show)


def plot_score_distribution(results, save_path, title_suffix=""):
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(results["anomaly_real"], bins=40, alpha=0.6,
            label="Reference", color="tab:green")
    ax.hist(results["anomaly_generated"], bins=40, alpha=0.6,
            label="Generated", color="tab:red")
    ax.axvline(results["threshold_p5"], color="tab:blue", linestyle=":",
               label=f"P5 = {results['threshold_p5']:.3f}")
    ax.axvline(results["threshold_3sigma"], color="black", linestyle="--",
               label=f"estad. = {results['threshold_3sigma']:.3f}")
    ax.set_title(f"Distribución de anomaly scores{title_suffix}")
    ax.set_xlabel("Anomaly score (-critic)")
    ax.set_ylabel("Frecuencia")
    ax.legend()
    ax.grid(True, linestyle="--", alpha=0.3)
    save_figure(fig, save_path)


def plot_roc_pr(results, save_path, title_suffix=""):
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    axes[0].plot(results["roc_fpr"], results["roc_tpr"],
                 label=f"AUC = {results['roc_auc']:.3f}", color="tab:blue")
    axes[0].plot([0, 1], [0, 1], linestyle="--", color="gray")
    axes[0].set_xlabel("False Positive Rate")
    axes[0].set_ylabel("True Positive Rate")
    axes[0].set_title(f"ROC{title_suffix}")
    axes[0].legend()
    axes[0].grid(True, linestyle="--", alpha=0.3)

    axes[1].plot(results["pr_recall"], results["pr_precision"],
                 label=f"AP = {results['pr_auc']:.3f}", color="tab:orange")
    axes[1].set_xlabel("Recall")
    axes[1].set_ylabel("Precision")
    axes[1].set_title(f"Precision-Recall{title_suffix}")
    axes[1].legend()
    axes[1].grid(True, linestyle="--", alpha=0.3)
    save_figure(fig, save_path)


def plot_roc_only(results, save_path, title="ROC Curve"):
   #roc
    fig, ax = plt.subplots(figsize=(7, 6))
    ax.plot(results["roc_fpr"], results["roc_tpr"],
            label=f"AUC = {results['roc_auc']:.3f}",
            color="tab:blue", linewidth=2)
    ax.plot([0, 1], [0, 1], linestyle="--", color="gray", label="Random")
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.set_title(title)
    ax.legend(loc="lower right")
    ax.grid(True, linestyle="--", alpha=0.3)
    save_figure(fig, save_path)


def plot_real_samples_from_test(test_loader, save_path, value_range, n_show=4):
    #plot de muestras mem
    imgs = next(iter(test_loader))[:n_show, 0].cpu().numpy()
    plot_samples_grid(imgs, save_path,
                      "Muestras reales",
                      value_range=value_range, n_show=n_show)


def plot_generated_samples_named(generator, latent_dim, device, save_path,
                                 value_range, n_show=4):
#plot muestras generadas
    generator.eval()
    with torch.no_grad():
        z = torch.randn(n_show, latent_dim, device=device)
        imgs = generator(z).cpu().numpy()[:, 0]
    plot_samples_grid(imgs, save_path,
                      "Muestras sintéticas",
                      value_range=value_range, n_show=n_show)

def compute_attacker_stats(real_hists_arr, generated_hists_arr):
    #calculo parametros muestras generadass

    real_flat = np.asarray(real_hists_arr).reshape(-1).astype(np.float64)
    gen_flat = np.asarray(generated_hists_arr).reshape(-1).astype(np.float64)
    return {
        "real_test": {
            "mean": float(np.mean(real_flat)),
            "std": float(np.std(real_flat)),
            "min": float(np.min(real_flat)),
            "max": float(np.max(real_flat)),
            "n_samples": int(real_hists_arr.shape[0]),
        },
        "generated": {
            "mean": float(np.mean(gen_flat)),
            "std": float(np.std(gen_flat)),
            "min": float(np.min(gen_flat)),
            "max": float(np.max(gen_flat)),
            "n_samples": int(generated_hists_arr.shape[0]),
        },
        "absolute_differences": {
            "mean": float(abs(np.mean(real_flat) - np.mean(gen_flat))),
            "std": float(abs(np.std(real_flat) - np.std(gen_flat))),
        },
    }


def build_metrics_json(split_info, attacker_stats, results_A):

    def defender_block(res):
        return {
            "score_distribution": {
                "real_test":  {"mean": res["mean_real"],
                               "std": res["std_real"]},
                "generated":  {"mean": res["mean_generated"],
                               "std": res["std_generated"]},
            },
            "roc_auc": res["roc_auc"],
            "pr_auc": res["pr_auc"],
            "best_f1": {
                "f1": res["best_f1"],
                "precision": res["best_precision"],
                "recall": res["best_recall"],
                "threshold": res["best_threshold"],
            },
            "threshold_percentile_5": res["metrics_p5"],
            "threshold_mu_plus_3sigma": res["metrics_3sigma"],
        }

    return {
        "split": split_info,
        "attacker": attacker_stats,
        "defender_components_A": defender_block(results_A),
    }

#guardar modelos, puntuacion y perdidas
def save_all_artifacts(generator, critic, history,
                       results_A,
                       train_loader, test_loader, split_info,
                       attacker_stats,
                       save_dir, latent_dim, value_range, device):
    models_dir = os.path.join(save_dir, "models")
    figs_dir = os.path.join(save_dir, "figures")

    torch.save(generator.state_dict(), os.path.join(models_dir, "generator.pth"))
    torch.save(critic.state_dict(), os.path.join(models_dir, "critic.pth"))
    print(f"Saved models to {models_dir}")

    np.save(
        os.path.join(save_dir, "training_losses.npy"),
        {k: np.array(v) for k, v in history.items()},
        allow_pickle=True,
    )

    np.savez(
        os.path.join(save_dir, "scores.npz"),
        real=-results_A["anomaly_real"],
        generated=-results_A["anomaly_generated"],
    )

    with open(os.path.join(save_dir, "results_summary.json"), "w") as f:
        json.dump(serializable_subset(results_A), f, indent=2)

    metrics_struct = build_metrics_json(split_info, attacker_stats, results_A)
    with open(os.path.join(save_dir, "metrics.json"), "w") as f:
        json.dump(metrics_struct, f, indent=2)
    print(f"Saved structured metrics.json")

    text_full = build_metrics_text(
        results_A,
        header="EVALUACIÓN",
    )
    with open(os.path.join(save_dir, "metrics.txt"), "w") as f:
        f.write(text_full)

    plot_training_losses(history, os.path.join(figs_dir, "training_losses.png"))
    plot_score_evolution(history, os.path.join(figs_dir, "score_evolution.png"))
    plot_score_distribution(
        results_A,
        os.path.join(figs_dir, "score_distribution.png"),
        title_suffix=" — test set",
    )
    plot_roc_pr(
        results_A,
        os.path.join(figs_dir, "roc_pr_curves.png"),
        title_suffix=" (test set)",
    )
    plot_roc_only(
        results_A,
        os.path.join(figs_dir, "roc_curve.png"),
        title="ROC — Defensor (crítico WGAN-GP) sobre test set",
    )

    # Muestras: 4 muestras en grid 2×2 (formato definitivo para la memoria)
    plot_real_samples_from_test(
        test_loader,
        os.path.join(figs_dir, "real_samples.png"),
        value_range=value_range,
        n_show=4,
    )
    plot_generated_samples_named(
        generator, latent_dim, device,
        os.path.join(figs_dir, "generated_samples.png"),
        value_range=value_range,
        n_show=4,
    )

    print(f"All artifacts saved to {save_dir}\n")
    print(text_full)

#guardar JSON
def serializable_subset(results):
    keys = ["roc_auc", "pr_auc",
            "mean_real", "std_real", "mean_generated", "std_generated",
            "threshold_p5", "threshold_3sigma",
            "best_threshold", "best_precision", "best_recall", "best_f1",
            "metrics_p5", "metrics_3sigma", "metrics_best"]
    return {k: results[k] for k in keys}


def build_metrics_text(results, header=""):
    lines = []
    if header:
        lines.append(header)
        lines.append("-" * len(header))
    lines.extend([
        f"ROC AUC: {results['roc_auc']:.4f}",
        f"PR AUC: {results['pr_auc']:.4f}",
        f"Mean anomaly score (reference):  {results['mean_real']:.4f} (std {results['std_real']:.4f})",
        f"Mean anomaly score (generated):  {results['mean_generated']:.4f} (std {results['std_generated']:.4f})",
        "",
        f"Best F1: {results['best_f1']:.4f} @ threshold = {results['best_threshold']:.4f}",
        f"  Precision: {results['metrics_best']['precision']:.4f} | "
        f"Recall: {results['metrics_best']['recall']:.4f}",
        "",
        f"Threshold percentil 5 (sobre reference): {results['threshold_p5']:.4f}",
        f"  Detection rate: {results['metrics_p5']['detection_rate']:.4f} | "
        f"FPR: {results['metrics_p5']['fpr']:.4f}",
        f"Threshold estad (sobre reference): {results['threshold_3sigma']:.4f}",
        f"  Detection rate: {results['metrics_3sigma']['detection_rate']:.4f} | "
        f"FPR: {results['metrics_3sigma']['fpr']:.4f}",
    ])
    return "\n".join(lines)

def run_experiment():
    print("=" * 60)
    print("WGAN-GP convolucional")
    print("Reference vs generated")
    print("=" * 60)
#split
    train_keys, test_keys = compute_train_test_split(
        REFERENCE_FOLDER,
        test_fraction=TEST_FRACTION,
        seed=SPLIT_SEED,
        min_points=MIN_POINTS,
    )

    # Datasets y loaders
    train_dataset, train_loader = build_dataloader(
        REFERENCE_FOLDER,
        batch_size=BATCH_SIZE,
        shuffle=True,
        resolution=RESOLUTION,
        value_range=VALUE_RANGE,
        min_points=MIN_POINTS,
        allowed_keys=train_keys,
    )
    test_dataset, test_loader = build_dataloader(
        REFERENCE_FOLDER,
        batch_size=BATCH_SIZE,
        shuffle=False,
        resolution=RESOLUTION,
        value_range=VALUE_RANGE,
        min_points=MIN_POINTS,
        allowed_keys=test_keys,
    )
    n_test = len(test_dataset)
    if n_test == 0:
        raise RuntimeError("No test samples loaded.")
    if len(train_dataset) == 0:
        raise RuntimeError("No train samples loaded.")

    split_info = {
        "test_fraction": TEST_FRACTION,
        "seed": SPLIT_SEED,
        "n_train_samples": len(train_dataset),
        "n_test_samples": n_test,
        "min_points": MIN_POINTS,
    }
    print(f"Train samples: {len(train_dataset)} | Test samples: {n_test}")

    # modelos y optimizadores
    generator = Generator(latent_dim=LATENT_DIM).to(device)
    critic = Critic().to(device)
    optimizer_G = torch.optim.Adam(generator.parameters(), lr=1e-4, betas=(0.5, 0.9))
    optimizer_C = torch.optim.Adam(critic.parameters(), lr=1e-4, betas=(0.5, 0.9))

    # Entrenamiento
    history = train_wgan_gp(
        generator, critic, train_loader, optimizer_G, optimizer_C,
        NUM_EPOCHS, LATENT_DIM, device,
        lambda_gp=LAMBDA_GP, n_critic=N_CRITIC,
    )

    # eval
    print("\n--- Evaluación ---")
    scores_real_A, scores_gen_A = evaluate_components(
        generator, critic, test_loader, LATENT_DIM, n_test, device
    )
    results_A = compute_metrics(scores_real_A, scores_gen_A, THRESHOLD_PERCENTILE)

    # stats del atacante
    print("\n--- Estadísticos del atacante ---")
    real_hists_test = np.stack(test_dataset.data, axis=0)
    generator.eval()
    with torch.no_grad():
        z_eval = torch.randn(n_test, LATENT_DIM, device=device)
        gen_hists = generator(z_eval).cpu().numpy()[:, 0]
    attacker_stats = compute_attacker_stats(real_hists_test, gen_hists)
    print(f"Real test:  mean={attacker_stats['real_test']['mean']:.4f}, "
          f"std={attacker_stats['real_test']['std']:.4f}, "
          f"min={attacker_stats['real_test']['min']:.4f}, "
          f"max={attacker_stats['real_test']['max']:.4f}")
    print(f"Generated:  mean={attacker_stats['generated']['mean']:.4f}, "
          f"std={attacker_stats['generated']['std']:.4f}, "
          f"min={attacker_stats['generated']['min']:.4f}, "
          f"max={attacker_stats['generated']['max']:.4f}")


    save_all_artifacts(
        generator, critic, history,
        results_A,
        train_loader, test_loader, split_info,
        attacker_stats,
        SAVE_DIR, LATENT_DIM, VALUE_RANGE, device,
    )

    return generator, critic, history, results_A, split_info, attacker_stats

def run_saved_model_evaluation():
    #Re-genera la evaluación sin reentrenar.

    train_keys, test_keys = compute_train_test_split(
        REFERENCE_FOLDER,
        test_fraction=TEST_FRACTION,
        seed=SPLIT_SEED,
        min_points=MIN_POINTS,
    )
    train_dataset, train_loader = build_dataloader(
        REFERENCE_FOLDER,
        batch_size=BATCH_SIZE,
        shuffle=False,
        resolution=RESOLUTION,
        value_range=VALUE_RANGE,
        min_points=MIN_POINTS,
        allowed_keys=train_keys,
    )
    test_dataset, test_loader = build_dataloader(
        REFERENCE_FOLDER,
        batch_size=BATCH_SIZE,
        shuffle=False,
        resolution=RESOLUTION,
        value_range=VALUE_RANGE,
        min_points=MIN_POINTS,
        allowed_keys=test_keys,
    )
    n_test = len(test_dataset)
    split_info = {
        "test_fraction": TEST_FRACTION,
        "seed": SPLIT_SEED,
        "n_train_samples": len(train_dataset),
        "n_test_samples": n_test,
        "min_points": MIN_POINTS,
    }

    generator = Generator(latent_dim=LATENT_DIM).to(device)
    critic = Critic().to(device)
    generator.load_state_dict(torch.load(
        os.path.join(SAVE_DIR, "models", "generator.pth"),
        map_location=device,
    ))
    critic.load_state_dict(torch.load(
        os.path.join(SAVE_DIR, "models", "critic.pth"),
        map_location=device,
    ))
    generator.eval(); critic.eval()

    history_path = os.path.join(SAVE_DIR, "training_losses.npy")
    if os.path.exists(history_path):
        h_dict = np.load(history_path, allow_pickle=True).item()
        history = {k: list(v) for k, v in h_dict.items()}
    else:
        print("Warning: training_losses.npy not found, history plots will be empty")
        history = {"loss_G": [], "loss_D": [],
                   "real_score": [], "fake_score": [], "critic_gap": []}

    scores_real_A, scores_gen_A = evaluate_components(
        generator, critic, test_loader, LATENT_DIM, n_test, device
    )
    results_A = compute_metrics(scores_real_A, scores_gen_A, THRESHOLD_PERCENTILE)

    real_hists_test = np.stack(test_dataset.data, axis=0)
    with torch.no_grad():
        z_eval = torch.randn(n_test, LATENT_DIM, device=device)
        gen_hists = generator(z_eval).cpu().numpy()[:, 0]
    attacker_stats = compute_attacker_stats(real_hists_test, gen_hists)

    save_all_artifacts(
        generator, critic, history,
        results_A,
        train_loader, test_loader, split_info,
        attacker_stats,
        SAVE_DIR, LATENT_DIM, VALUE_RANGE, device,
    )
    return generator, critic, history, results_A, split_info, attacker_stats

#entrenr
generator, critic, history, results_A, split_info, attacker_stats = run_experiment()

#reevaluar sin reentrenar
generator, critic, history, results_A, split_info, attacker_stats = run_saved_model_evaluation()
