# -*- coding: utf-8 -*-
"""DISTRIBUTED_GAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eAve8nSqzgpIYmRXVv6AQHcWIXBlv8ZZ
"""

import numpy as np
import matplotlib.pyplot as plt
import sys
import os
import torch
import pandas as pd

from scipy.ndimage import gaussian_filter
from keras.models import Sequential
from keras.layers import Dense, Activation, LeakyReLU
from keras.optimizers import Adam
from torch.utils.data import Dataset
from keras import backend as K

from google.colab import drive
drive.mount('/content/drive')

def create_histogram(
    x,
    y,
    resolution=64,
    value_range=(-1,1)
):
#crear imagen
    H, _, _ = np.histogram2d(
        x,
        y,
        bins=resolution,
        range=[
            [value_range[0], value_range[1]],
            [value_range[0], value_range[1]]
        ]
    )
#Normalización
    if H.max() > 0:
        H = H / H.max()
#Ajuste a [-1,1] para tanh de GAN
    H = H * 2 - 1

    return H

class ClusterDataset(Dataset):
    def __init__(self, files, folder, q, resolution):
#Leemos CSV, extraemos puntos IQ, convertimos a histograma y creamos Dataset para GAN
        self.data = []

        for file in files:

            path = os.path.join(folder, file)
            df = pd.read_csv(path)

            for sample_id in df["Sample_Id"].unique():

                df_sample = df[df["Sample_Id"] == sample_id]
                cluster = df_sample[df_sample["Q"] == q]

                x = cluster["X_norm"].values
                y = cluster["Y_norm"].values

                if len(x) < 10: #per clusters que tenen pocs punts
                  continue

                H = create_histogram(
                    x,
                    y,
                    resolution
                )
                self.data.append(H)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img = torch.tensor(self.data[idx], dtype=torch.float32).unsqueeze(0)
        return img

data_ref_path = "/content/drive/MyDrive/TFG/data_processed/reference_clusters"
data_alt_path = "/content/drive/MyDrive/TFG/data_processed/altered_clusters"
files_ref = sorted(os.listdir(data_ref_path))
files_alt = sorted(os.listdir(data_alt_path))

print("Número de archivos:", len(files_ref))

#for f in files_ref:
#    print(f)

print("Número de archivos:", len(files_alt))
#for f in files_alt:
 #   print(f)

q = 0                # cluster a analizar
resolution = 64

dataset = ClusterDataset(files_ref, data_ref_path, q, resolution=resolution)
dataset_alt= ClusterDataset(files_alt, data_alt_path, q, resolution=resolution)

def load_data(dataset):
    data = []
    for i in range(len(dataset)):
        img = dataset[i][0].numpy()
        img = img.squeeze()
        data.append(img)
    return np.array(data)

X_train = load_data(dataset)
X_altered = load_data(dataset_alt)

print("Dataset shape:", X_train.shape)
print ("Dataset altered shape: ", X_altered.shape)

#imagenes 64x64 a vectores de resolution*resolution
def preprocess(x):
    x = x.reshape(-1, resolution*resolution)
    x = np.float64(x)
    return x

X_train_real = preprocess(X_train)
X_train_altered = preprocess(X_altered)
print(X_train_real.shape)
print(X_train_altered.shape)

def make_latent_samples(n_samples, sample_size):
    #return np.random.uniform(-1, 1, size=(n_samples, sample_size))
    return np.random.normal(loc=0, scale=1, size=(n_samples, sample_size))

def make_labels(size):
    return np.ones([size, 1]), np.zeros([size, 1])

def make_trainable(model, trainable):
    for layer in model.layers:
        layer.trainable = trainable

def make_simple_GAN(sample_size,
                    g_hidden_size,
                    d_hidden_size,
                    leaky_alpha,
                    g_learning_rate,
                    d_learning_rate):
    K.clear_session()

    generator = Sequential([
        Dense(g_hidden_size, input_shape=(sample_size,)),
        LeakyReLU(alpha=leaky_alpha),
        Dense(resolution*resolution),
        Activation('tanh')
    ], name='generator')

    discriminator = Sequential([
        Dense(d_hidden_size, input_shape=(resolution*resolution,)),
        LeakyReLU(alpha=leaky_alpha),
        Dense(1),
        Activation('sigmoid')
    ], name='discriminator')

    gan = Sequential([
        generator,
        discriminator
    ])

    discriminator.compile(optimizer=Adam(learning_rate=d_learning_rate,beta_1=0.5), loss='binary_crossentropy')
    gan.compile(optimizer=Adam(learning_rate=g_learning_rate,beta_1=0.5), loss='binary_crossentropy')

    return gan, generator, discriminator

#visualitzar valors (estem agafant nomes q = 0)
print("Shape X_train:", X_train.shape)
print("Min:", X_train.min())
print("Max:", X_train.max())

# hyperparameters
sample_size     = 100     # latent sample size (i.e., 100 random numbers)
g_hidden_size   = 256
d_hidden_size   = 256
leaky_alpha     = 0.2
g_learning_rate = 0.0002  # learning rate for the generator
d_learning_rate = 0.0002   # learning rate for the discriminator
epochs          = 500
batch_size      = 64      # train batch size
eval_size       = 16      # evaluate size
smooth          = 0.1

# labels for the batch size and the test size
y_train_real, y_train_fake = make_labels(batch_size)
y_eval_real,  y_eval_fake  = make_labels(eval_size)

# create a GAN, a generator and a discriminator
gan, generator, discriminator = make_simple_GAN(
    sample_size,
    g_hidden_size,
    d_hidden_size,
    leaky_alpha,
    g_learning_rate,
    d_learning_rate)

losses = []
for e in range(epochs):
    for i in range(len(X_train_real)//batch_size):

        X_batch_real = X_train_real[i*batch_size:(i+1)*batch_size]

        # latent samples and the generated  images
        latent_samples = make_latent_samples(batch_size, sample_size)
        X_batch_fake = generator.predict_on_batch(latent_samples)

        # train the discriminator to detect real and fake images
        make_trainable(discriminator, True)
        discriminator.train_on_batch(X_batch_real, y_train_real * (1 - smooth))
        discriminator.train_on_batch(X_batch_fake, y_train_fake)

        # train the generator via GAN
        make_trainable(discriminator, False)
        gan.train_on_batch(latent_samples, y_train_real)

    # evaluate
    X_eval_real = X_train_real[np.random.choice(len(X_train_real), eval_size, replace=False)]
    latent_samples = make_latent_samples(eval_size, sample_size)
    X_eval_fake = generator.predict_on_batch(latent_samples)

    d_loss  = discriminator.test_on_batch(X_eval_real, y_eval_real)
    d_loss += discriminator.test_on_batch(X_eval_fake, y_eval_fake)
    g_loss  = gan.test_on_batch(latent_samples, y_eval_real) # we want the fake to be realistic!

    losses.append((d_loss, g_loss))

    print("Epoch: {:>3}/{} Discriminator Loss: {:>6.4f} Generator Loss: {:>6.4f}".format(
        e+1, epochs, d_loss, g_loss))

losses = np.array(losses)

fig, ax = plt.subplots()
plt.plot(losses.T[0], label='Discriminator')
plt.plot(losses.T[1], label='Generator')
plt.title("Training Losses")
plt.legend()
plt.show()

def deprocess(x):
    x = (x + 1) / 2.0 * 255.0
    x = np.clip(x, 0, 255)
    x = np.uint8(x)
    x = x.reshape(resolution, resolution)
    return x

def get_scores(discriminator, X):
    return discriminator.predict(X).flatten()

#EVALUACION
# ---- 1. Scores en datos normales ----
scores_real = get_scores(discriminator, X_train_real)

# ---- 2. Calcular threshold ----
threshold_perc = np.percentile(scores_real, 5)
mu = np.mean(scores_real)
sigma = np.std(scores_real)

threshold_stat = mu - 3 * sigma

print(f"Threshold (5th percentile): {threshold_perc:.4f}")
print(f"Threshold (stadistic): {threshold_stat:.4f}")

# ---- 3. Scores en datos alterados ----

X_altered = preprocess(X_altered)
scores_altered = get_scores(discriminator, X_altered)

# ---- 4. Detección ----
det_stat = np.mean(scores_altered < threshold_stat)
det_perc = np.mean(scores_altered < threshold_perc)

print(f"Detection rate: {det_stat:.4f}")
print(f"Detection rate (5th percentile): {det_perc:.4f}")

import matplotlib.pyplot as plt

plt.hist(scores_real, bins=50, alpha=0.5, label='Real')
plt.hist(scores_altered, bins=50, alpha=0.5, label='Altered')
plt.axvline(threshold_stat, color='green', linestyle='--', linewidth=2, label='μ - 3σ')
plt.axvline(threshold_perc, color='red', linestyle='--', linewidth=2, label='Percentile (5%)')
plt.legend()
plt.title("Score distribution")
plt.show()

#EJEMPLO DE IMAGENES GENERADAS POR EL GENERADOR
latent_samples = make_latent_samples(20, sample_size)
generated_digits = generator.predict(latent_samples)

plt.figure(figsize=(10, 8))

for i in range(20):

    img = deprocess(generated_digits[i])

    plt.subplot(4, 5, i+1)
    plt.imshow(img, cmap='gray')

    plt.xticks([])
    plt.yticks([])

plt.tight_layout()
plt.show()

def histogram_to_iq_points(
    hist,
    num_points=128,
    value_range=(-1, 1)
):

    # -----------------------------
    # Eliminar dimensión extra
    # -----------------------------
    if len(hist.shape) == 3:
        hist = hist.squeeze()

    # -----------------------------
    # Convertir [-1,1] → [0,1]
    # -----------------------------
    hist = (hist + 1) / 2

    # -----------------------------
    # Evitar negativos
    # -----------------------------
    hist = np.clip(hist, 0, None)

    # -----------------------------
    # Normalizar como probabilidad
    # -----------------------------
    prob = hist / np.sum(hist)

    resolution = hist.shape[0]

    # -----------------------------
    # Crear índices planos
    # -----------------------------
    flat_prob = prob.flatten()

    # -----------------------------
    # Sampling probabilístico
    # -----------------------------
    sampled_idx = np.random.choice(
        len(flat_prob),
        size=num_points,
        p=flat_prob
    )

    # -----------------------------
    # Convertir índices → coordenadas 2D
    # -----------------------------
    rows, cols = np.unravel_index(sampled_idx, (resolution, resolution))

    # -----------------------------
    # Convertir píxeles → coordenadas IQ
    # -----------------------------
    min_val, max_val = value_range

    x = min_val + (cols / resolution) * (max_val - min_val)
    y = min_val + (rows / resolution) * (max_val - min_val)

    # -----------------------------
    # Añadir jitter sub-píxel
    # -----------------------------
    pixel_size = (max_val - min_val) / resolution

    x += np.random.uniform(-pixel_size/2, pixel_size/2, size=num_points)
    y += np.random.uniform(-pixel_size/2, pixel_size/2, size=num_points)

    return x, y

def iq_to_histogram(
    x,
    y,
    resolution=64,
    value_range=(-1,1)
):

    return create_histogram(
    x,
    y,
    resolution,
    value_range
)

#VISUALIZACION FLUJO SISTEMA
#primer sample de los generados lo pasamos a histograma de res*res
generated_hist = generated_digits[0]
generated_hist = generated_hist.reshape(
    resolution,
    resolution
)

# histograma → IQ (SALIDA GENERADOR)
x_fake, y_fake = histogram_to_iq_points(
    generated_hist,
    num_points=128
)

# IQ → histograma (ENTRADA DISCRIMINADOR)
reconstructed_hist = iq_to_histogram(
    x_fake,
    y_fake,
    resolution=resolution
)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.imshow(
    generated_hist,
    cmap='viridis',
    vmin=-1,
    vmax=1
)
plt.title("Original Generated Histogram")

plt.subplot(1,2,2)
plt.imshow(
    reconstructed_hist,
    cmap='viridis',
    vmin=-1,
    vmax=1
)
plt.title("Reconstructed From IQ")

plt.show()

# ----------------------------------
# IQ → histograma detector (ENTRADA DISCRIMINADOR)
# ----------------------------------

detector_hist = iq_to_histogram(
    x_fake,
    y_fake,
    resolution=resolution
)

detector_input = detector_hist.reshape(
    1,
    resolution * resolution
)

score = discriminator.predict(detector_input)

print("Detection score:", score[0][0])

class GeneratorAgent:

    def __init__(
        self,
        generator,
        sample_size,
        resolution
    ):

        self.generator = generator
        self.sample_size = sample_size
        self.resolution = resolution

    def generate(self,
                 num_points=128):

        latent = make_latent_samples(
            1,
            self.sample_size
        )
        #genera una predicción sintetica gracias al entreno previo
        generated_hist = self.generator.predict(latent)[0]
        # 64x64
        generated_hist = generated_hist.reshape(
            self.resolution,
            self.resolution
        )

        x_fake, y_fake = histogram_to_iq_points(
            generated_hist,
            num_points=num_points
        )

        return {
            "x": x_fake,
            "y": y_fake
        }

class DetectorAgent:

    def __init__(
        self,
        discriminator,
        resolution
    ):

        self.discriminator = discriminator
        self.resolution = resolution

    def detect(
        self,
        x,
        y
    ):

        H = iq_to_histogram(
            x,
            y,
            resolution=self.resolution
        )

        H_input = H.reshape(
            1,
            self.resolution * self.resolution
        )

        score = self.discriminator.predict(H_input)

        return score[0][0]

generator_agent = GeneratorAgent(
    generator,
    sample_size,
    resolution
)

detector_agent = DetectorAgent(
    discriminator,
    resolution
)

message = generator_agent.generate()

score = detector_agent.detect(
    message["x"],
    message["y"]
)

print("Distributed score:", score)

n_samples = 100

correct = 0
wrong = 0

scores = []

for i in range(n_samples):

    # -------------------------
    # Generador distribuido
    # -------------------------
    message = generator_agent.generate()

    # -------------------------
    # Detector distribuido
    # -------------------------
    score = detector_agent.detect(
        message["x"],
        message["y"]
    )

    scores.append(score)

    # -------------------------
    # Evaluación
    # -------------------------
    if score < threshold_perc:

        # Detectó correctamente fake/anomalía
        correct += 1

    else:

        # Pensó que era legítimo
        wrong += 1

accuracy = correct / n_samples

print("Correct detections:", correct)
print("Wrong detections:", wrong)
print("Detection accuracy:", accuracy)