# -*- coding: utf-8 -*-
"""PointGAN_git.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4lqQ3kaNyNvQmGT0wjJ5vXefkZ9_wpu
"""

import os
import re
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from IPython.display import display
from sklearn.metrics import roc_curve, roc_auc_score

from google.colab import drive
drive.mount('/content/drive')

#   "A_no_beacons"   -> solo disc_only
#   "B_with_beacons" -> con balizas : Modos validos: "beacon_only", "disc_only", "or".

EXPERIMENT_TYPE = "B_with_beacons"
EXPERIMENT_MODE = "or"

VALID_TYPES = ["A_no_beacons", "B_with_beacons"]
if EXPERIMENT_TYPE not in VALID_TYPES:
    raise ValueError(f"EXPERIMENT_TYPE debe estar en {VALID_TYPES}")

if EXPERIMENT_TYPE == "A_no_beacons":
    USE_BEACONS_IN_TRAIN = False
    INJECT_BEACONS_AT_EVAL = False
    MODEL_NAME = "pointgan_no_beacons"
    if EXPERIMENT_MODE != "disc_only":
        raise ValueError(
            f"Con EXPERIMENT_TYPE='A_no_beacons' solo se admite EXPERIMENT_MODE='disc_only'. "
            f"Recibido: '{EXPERIMENT_MODE}'."
        )
else:
    USE_BEACONS_IN_TRAIN = True
    INJECT_BEACONS_AT_EVAL = True
    MODEL_NAME = "pointgan_with_beacons"
    VALID_MODES_B = ["beacon_only", "disc_only", "or"]
    if EXPERIMENT_MODE not in VALID_MODES_B:
        raise ValueError(
            f"Con EXPERIMENT_TYPE='B_with_beacons' los modos validos son {VALID_MODES_B}. "
            f"Recibido: '{EXPERIMENT_MODE}'."
        )

CONFIG_NAME = EXPERIMENT_MODE

print(f"EXPERIMENT_TYPE        = {EXPERIMENT_TYPE}")
print(f"EXPERIMENT_MODE        = {EXPERIMENT_MODE}")
print(f"MODEL_NAME             = {MODEL_NAME}")
print(f"USE_BEACONS_IN_TRAIN   = {USE_BEACONS_IN_TRAIN}")
print(f"INJECT_BEACONS_AT_EVAL = {INJECT_BEACONS_AT_EVAL}")


DATA_PATH = "/content/drive/MyDrive/TFG/data_processed/reference_clusters"
GENERATED_PATH = f"/content/drive/MyDrive/TFG/data_processed/generated/{MODEL_NAME}"

POINTGAN_ROOT = "/content/drive/MyDrive/TFG/pointgan"
MODELS_DIR = os.path.join(POINTGAN_ROOT, "models")
RESULTS_DIR = os.path.join(POINTGAN_ROOT, "results")
FIGURES_DIR = os.path.join(POINTGAN_ROOT, "figures")
LOGS_DIR = os.path.join(POINTGAN_ROOT, "logs")
CONFIGS_DIR = os.path.join(POINTGAN_ROOT, "configs")

for dir_path in [POINTGAN_ROOT, MODELS_DIR, RESULTS_DIR, FIGURES_DIR, LOGS_DIR, CONFIGS_DIR, GENERATED_PATH]:
    os.makedirs(dir_path, exist_ok=True)

 #hiperparametros del sistema de balizas
Q_CLUSTERS = []
FI = 0.7
P_LOW = 1
P_HIGH = 99
ANGLES_DEG = [15, 140, 220, 300]

EPSILON_SHORT = 0.015
EPSILON_MID = 0.025
EPSILON_LONG = 0.05

DISTANCE_BINS = [
    (0, 720, "short"),
    (720, 1400, "mid"),
    (1400, 10000, "long"),
]
EPSILON_BY_GROUP = {
    "short": EPSILON_SHORT,
    "mid": EPSILON_MID,
    "long": EPSILON_LONG,
}


#hiperparametros GAN
POINTS_PER_SAMPLE = 2048
BATCH_SIZE = 16
EPOCHS = 200
LEARNING_RATE = 2e-4
LATENT_DIM = 128
SEED = 42



TEST_FRACTION = 0.2
N_FAKES = 500
N_FAKES_PER_DISTANCE = 10


P_THRESHOLD = 5
P_DISC_THRESHOLD = 5

torch.manual_seed(SEED)
np.random.seed(SEED)

#extrae num de dist
def parse_distance_from_source(source_file):
    match = re.search(r"source_(\d+)", source_file)
    if match is None:
        raise ValueError(f"Could not parse distance from {source_file}")
    return int(match.group(1))

#devuelve grupo distancia (para epsilon)
def group_for_distance(distance):
    for d_min, d_max, group in DISTANCE_BINS:
        if d_min <= distance < d_max:
            return group
    raise ValueError(f"Distance {distance} outside DISTANCE_BINS ranges")

#devuelve epsilon y grupo
def epsilon_for_distance(distance):
    group = group_for_distance(distance)
    return EPSILON_BY_GROUP[group], group

#combina para obtener epsilon, grupo y dist a partir del archivo
def epsilon_for_source(source_file):
    distance = parse_distance_from_source(source_file)
    eps, group = epsilon_for_distance(distance)
    return eps, group, distance


def list_source_files(data_path):
    files = [f for f in os.listdir(data_path) if f.startswith("source_") and f.endswith(".csv")]
    return sorted(files, key=parse_distance_from_source)


# Dentro de cada distancia, 80% train / 20% test
def build_train_test_split(data_path, test_fraction=TEST_FRACTION, seed=SEED):

    # {distance: {"train": [sample_ids], "test": [sample_ids]}}

    rng = np.random.default_rng(seed)
    split = {}
    for source_file in list_source_files(data_path):
        distance = parse_distance_from_source(source_file)
        path = os.path.join(data_path, source_file)
        df = pd.read_csv(path)
        sample_ids = sorted(df["Sample_Id"].unique())
        n = len(sample_ids)
        n_test = max(1, int(round(n * test_fraction)))
        shuffled = list(sample_ids)
        rng.shuffle(shuffled)
        test_ids = sorted(shuffled[:n_test])
        train_ids = sorted(shuffled[n_test:])

        # Verificaciones defensivas
        assert set(train_ids).isdisjoint(set(test_ids)), f"Distancia {distance}: train y test NO disjuntos"
        assert len(train_ids) + len(test_ids) == n, f"Distancia {distance}: train+test != total"

        split[distance] = {"train": train_ids, "test": test_ids}
    return split

#filtra samples dentro de una distancia (dependiendo particion)
def filter_samples_by_split(df, source_file, split_dict, partition="train"):

    distance = parse_distance_from_source(source_file)
    if distance not in split_dict:
        return df.iloc[0:0]
    valid_ids = set(split_dict[distance][partition])
    return df[df["Sample_Id"].isin(valid_ids)]


# Construir el split
train_test_split = build_train_test_split(DATA_PATH)
total_train = sum(len(v["train"]) for v in train_test_split.values())
total_test = sum(len(v["test"]) for v in train_test_split.values())
print(f"Train samples: {total_train}")
print(f"Test samples:  {total_test}")
print(f"Distancias:    {len(train_test_split)}")
for d in sorted(train_test_split.keys())[:3]:
    print(f"  Lb={d}: train={len(train_test_split[d]['train'])} test={len(train_test_split[d]['test'])}")

def generate_beacon_positions(
    x,
    y,
    fi=0.7,
    angles=None,
    p_low=1,
    p_high=99
):
 #funcion que genera puntos baliza a partir de las coord. normalizadas

    x = np.asarray(x)
    y = np.asarray(y)

    if angles is None:
        angles = np.linspace(0, 2 * np.pi, 4, endpoint=False)

    x_min = np.percentile(x, p_low)
    x_max = np.percentile(x, p_high)
    y_min = np.percentile(y, p_low)
    y_max = np.percentile(y, p_high)

    cx = (x_min + x_max) / 2.0
    cy = (y_min + y_max) / 2.0
    #agafa el radi minim des del centre dels percentils a un dels punts dels percentils
    r = min(
        abs(x_max - cx),
        abs(cx - x_min),
        abs(y_max - cy),
        abs(cy - y_min),
    )
    #reduccio radi
    r2 = fi * r
    beacon_points = []
    for theta in angles:
        bx = cx + r2 * np.cos(theta)
        by = cy + r2 * np.sin(theta)
        beacon_points.append([bx, by])

    beacon_points = np.asarray(beacon_points)
    metadata = {
        "center": (cx, cy),
        "radius_original": r,
        "radius_reduced": r2,
        "bounds": {
            "x_min": x_min,
            "x_max": x_max,
            "y_min": y_min,
            "y_max": y_max,
        },
    }

    return beacon_points, metadata

def count_beacons(
    x,
    y,
    beacon_points,
    epsilon=0.03
):

    x = np.asarray(x)
    y = np.asarray(y)
    #ajunta punts en un vector x,y
    points = np.column_stack([x, y])
    detected = []
    #calcula distancia entre punts i balisses, si es menor a epsilon es considera detectat
    for i, beacon in enumerate(beacon_points):
        distances = np.linalg.norm(points - beacon, axis=1)
        if np.any(distances < epsilon):
            detected.append(i)

    return len(detected), detected

# Posiciones de balizas por distancia (B)

def build_fixed_beacons_per_distance(reference_path, split_dict=None, partition="train"):

    angles_rad = np.deg2rad(ANGLES_DEG)
    beacons_per_distance = {}

    for source_file in list_source_files(reference_path):
        distance = parse_distance_from_source(source_file)
        path = os.path.join(reference_path, source_file)
        df = pd.read_csv(path)

        if split_dict is not None:
            df = filter_samples_by_split(df, source_file, split_dict, partition)
        if df.empty:
            continue

        if Q_CLUSTERS:
            q_values = Q_CLUSTERS
        else:
            q_values = sorted(df["Q"].unique())

        beacons_per_cluster = {}
        for q in q_values:
            cluster_df = df[df["Q"] == q]
            if cluster_df.empty:
                continue
            points, _ = generate_beacon_positions(
                cluster_df["X_norm"].values,
                cluster_df["Y_norm"].values,
                fi=FI,
                angles=angles_rad,
                p_low=P_LOW,
                p_high=P_HIGH,
            )
            beacons_per_cluster[int(q)] = points
        beacons_per_distance[int(distance)] = beacons_per_cluster

    return beacons_per_distance
    #devuelve el mapa de balizas


if EXPERIMENT_TYPE == "B_with_beacons":
    print("Building fixed beacons per distance from TRAIN reference...")
    fixed_beacons = build_fixed_beacons_per_distance(DATA_PATH, split_dict=train_test_split, partition="train")
    print(f"  Distances with beacons: {sorted(fixed_beacons.keys())}")
    if 80 in fixed_beacons:
        print(f"  Clusters in dist=80: {sorted(fixed_beacons[80].keys())}")
else:
    print(f"EXPERIMENT_TYPE='{EXPERIMENT_TYPE}': sin balizas (skipping beacon construction).")
    fixed_beacons = {}

# Threshold de balizas por distancia (legitimas sin marcar)


if EXPERIMENT_TYPE == "B_with_beacons":
    anchor_results = []

    for source_file in list_source_files(DATA_PATH):
        path = os.path.join(DATA_PATH, source_file)
        df = pd.read_csv(path)

        df = filter_samples_by_split(df, source_file, train_test_split, partition="train")
        if df.empty:
            continue

        eps, group, distance = epsilon_for_source(source_file)
        beacons_this_dist = fixed_beacons.get(distance, {})
        if not beacons_this_dist:
            continue

        sample_ids = sorted(df["Sample_Id"].unique())
        for sample_id in sample_ids:
            sample_df = df[df["Sample_Id"] == sample_id]

            v_total = 0
            for q, beacon_positions in beacons_this_dist.items():
                cluster_df = sample_df[sample_df["Q"] == q]
                if cluster_df.empty:
                    continue
                count, _ = count_beacons(
                    cluster_df["X_norm"].values,
                    cluster_df["Y_norm"].values,
                    beacon_positions,
                    epsilon=eps,
                )
                v_total += count

            anchor_results.append({
                "source": source_file,
                "distance": distance,
                "group": group,
                "epsilon": eps,
                "sample_id": sample_id,
                "v_score_sum": v_total,
            })

    anchor_df = pd.DataFrame(anchor_results)
    print(f"Total anchor rows (TRAIN unmarked samples): {len(anchor_df)}")

    anchor_summary = (
        anchor_df
        .groupby(["source", "distance", "group", "epsilon"])
        .agg(
            v_mean=("v_score_sum", "mean"),
            v_std=("v_score_sum", "std"),
            n=("v_score_sum", "size"),
        )
        .reset_index()
    )
    #es fa a partir del percentil 95 alt dels reference
    P_THRESHOLD_NOISE = 95

    threshold_by_dist = (
        anchor_df
        .groupby("distance")["v_score_sum"]
        .quantile(P_THRESHOLD_NOISE / 100.0)
        .to_dict()
    )
    anchor_summary["threshold"] = anchor_summary["distance"].map(threshold_by_dist)

    print("\nAnchor summary (per distance):")
    display(anchor_summary)
else:
    print(f"EXPERIMENT_TYPE='{EXPERIMENT_TYPE}': skipping beacon threshold calibration.")
    anchor_df = pd.DataFrame()
    anchor_summary = pd.DataFrame()
    threshold_by_dist = {}

#classe que ens serveix per a iterar als constellation points
class PointCloudDataset(Dataset):
    def __init__(self, points):
        self.points = points

    def __len__(self):
        return len(self.points)

    def __getitem__(self, idx):
        x = torch.from_numpy(self.points[idx])
        return x

class PointGANGenerator(nn.Module):
    def __init__(self, latent_dim, num_points):
        super().__init__()
        self.num_points = num_points
        self.net = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 512),
            nn.LeakyReLU(0.2),
            nn.Linear(512, 1024),
            nn.LeakyReLU(0.2),
            nn.Linear(1024, 2048),
            nn.LeakyReLU(0.2),
            nn.Linear(2048, num_points * 2),
        )

    def forward(self, z):
        x = self.net(z)
        return x.view(-1, self.num_points, 2)


class PointGANDiscriminator(nn.Module):
  """
  La xarxa MLP s'aplica a cada punt individual, s'extreu les característiques i
  s'agrega a un vector general a partir de max pooling. Aquest ultim passa pel classificador
  produint un valor logit, que passara per sigmoid i sera una probabilitat
  """
  def __init__(self, input_dim=2):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.LeakyReLU(0.2),
            nn.Linear(64, 128),
            nn.LeakyReLU(0.2),
            nn.Linear(128, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 512),
            nn.LeakyReLU(0.2),
        )
        self.fc = nn.Sequential(
            nn.Linear(1024, 256),  # 512 max + 512 mean = 1024
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.LeakyReLU(0.2),
            nn.Linear(128, 1),
        )

  def forward(self, x):
        x = self.mlp(x)                          # (batch, num_points, 512)
        x_max = torch.max(x, dim=1).values       # (batch, 512)
        x_mean = torch.mean(x, dim=1)            # (batch, 512)
        x_global = torch.cat([x_max, x_mean], dim=1)  # (batch, 1024)
        return self.fc(x_global).squeeze(1)

#creem dos maps: un dist--> thresh i un altre de grup per si a cas
def build_threshold_maps(anchor_summary_df):
    threshold_by_distance = {}
    if anchor_summary_df.empty:
        return threshold_by_distance, {}
    for _, row in anchor_summary_df.iterrows():
        threshold_by_distance[int(row["distance"])] = float(row["threshold"])
    group_threshold = (
        anchor_summary_df
        .groupby("group")["threshold"]
        .mean()
        .to_dict()
    )
    return threshold_by_distance, group_threshold

#retornem el threshold depenent de la dist, si no existeix el de grup
def threshold_for_distance(distance, threshold_by_distance, group_threshold):
    if not threshold_by_distance:
        return float("inf")  # En experimento A, threshold inalcanzable -> beacon nunca marca
    if distance in threshold_by_distance:
        return threshold_by_distance[distance]
    group = group_for_distance(distance)
    return float(group_threshold.get(group, float("inf")))


#normalitzar tamany nuvol a 2048
def sample_point_cloud(points, num_points, rng):
    if len(points) == 0:
        return np.zeros((num_points, 2), dtype=np.float32)
    if len(points) >= num_points:
        idx = rng.choice(len(points), size=num_points, replace=False)
        return points[idx].astype(np.float32)
    pad_idx = rng.choice(len(points), size=num_points - len(points), replace=True)
    padded = np.concatenate([points, points[pad_idx]], axis=0)
    return padded.astype(np.float32)


#centres
_CONSTELLATION_CENTERS_DICT = {
    0: (-3,-3),  1: (-3,-1),  2: (-3,1),  3: (-3,3),
    4: (-1,-3),  5: (-1,-1),  6: (-1,1),  7: (-1,3),
    8: ( 1,-3),  9: ( 1,-1), 10: ( 1,1), 11: ( 1,3),
   12: ( 3,-3), 13: ( 3,-1), 14: ( 3,1), 15: ( 3,3),
}


#injectar balisses (security local)
def inject_beacons_into_sample(sample_df, beacons_by_cluster):

    extra_rows = []
    next_symbol = int(sample_df["Symbol_Id"].max()) + 1
    sample_id = int(sample_df["Sample_Id"].iloc[0])

    for q, beacon_positions_local in beacons_by_cluster.items():
        cx, cy = _CONSTELLATION_CENTERS_DICT[int(q)]
        for (x_loc, y_loc) in beacon_positions_local:
            extra_rows.append({
                "Sample_Id": sample_id,
                "Symbol_Id": next_symbol,
                "Real": float(cx + x_loc),
                "Imag": float(cy + y_loc),
                "Q": int(q),
                "X_norm": float(x_loc),
                "Y_norm": float(y_loc),
            })
            next_symbol += 1

    return pd.concat([sample_df, pd.DataFrame(extra_rows)], ignore_index=True)


#cargar datos train (añadimos balizas)
def build_pointclouds_from_path(data_path, num_points, seed,
                                 inject_beacons_flag=False,
                                 fixed_beacons_dict=None,
                                 split_dict=None,
                                 partition="train"):
    rng = np.random.default_rng(seed)
    samples = []
    meta = []

    for source_file in list_source_files(data_path):
        path = os.path.join(data_path, source_file)
        df = pd.read_csv(path)

        if split_dict is not None:
            df = filter_samples_by_split(df, source_file, split_dict, partition)
        if df.empty:
            continue

        sample_ids = sorted(df["Sample_Id"].unique())
        distance = parse_distance_from_source(source_file)
        beacons_this_dist = (fixed_beacons_dict or {}).get(distance, {}) if inject_beacons_flag else {}

        for sample_id in sample_ids:
            sample_df = df[df["Sample_Id"] == sample_id]

            if inject_beacons_flag and beacons_this_dist:
                sample_df_marked = inject_beacons_into_sample(sample_df, beacons_this_dist)
                points = sample_df_marked[["Real", "Imag"]].values
            else:
                points = sample_df[["Real", "Imag"]].values

            pc = sample_point_cloud(points, num_points, rng)
            samples.append(pc.astype(np.float32))
            meta.append({
                "source": source_file,
                "distance": distance,
                "sample_id": sample_id,
            })

    return np.stack(samples), pd.DataFrame(meta)


#cuenta el num de balizas en una muestra
def beacon_score_sum_with_fixed_beacons(sample_df, beacons_per_cluster, eps):
    if not beacons_per_cluster:
        return 0
    total = 0
    for q, beacon_positions in beacons_per_cluster.items():
        cluster_df = sample_df[sample_df["Q"] == q]
        if cluster_df.empty:
            continue
        count, _ = count_beacons(
            cluster_df["X_norm"].values,
            cluster_df["Y_norm"].values,
            beacon_positions,
            epsilon=eps,
        )
        total += count
    return total


#para el detector, combina decision
def _resolve_final_flag(disc_flag, beacon_flag, experiment_mode):
    if experiment_mode == "disc_only":
        return bool(disc_flag)
    if experiment_mode == "beacon_only":
        return bool(beacon_flag)
    if experiment_mode == "and":
        return bool(disc_flag and beacon_flag)
    return bool(disc_flag or beacon_flag)  # "or"


# Evaluacion sobre reference test

def evaluate_reference_parallel(
    data_path,
    threshold_by_distance,
    group_threshold,
    disc_model,
    device,
    fixed_beacons,
    experiment_mode=EXPERIMENT_MODE,
    split_dict=None,
    partition="test",
    inject_at_eval=False,
):
    disc_model.eval()
    results = []
    rng = np.random.default_rng(SEED)

    with torch.no_grad():
        for source_file in list_source_files(data_path):
            path = os.path.join(data_path, source_file)
            df = pd.read_csv(path)

            if split_dict is not None:
                df = filter_samples_by_split(df, source_file, split_dict, partition)
            if df.empty:
                continue

            ref_distance = parse_distance_from_source(source_file)
            sample_ids = sorted(df["Sample_Id"].unique())

            for sample_id in sample_ids:
                sample_df = df[df["Sample_Id"] == sample_id]
                lb = ref_distance

                eps, _ = epsilon_for_distance(lb)
                threshold = threshold_for_distance(lb, threshold_by_distance, group_threshold)
                beacons_this_dist = fixed_beacons.get(lb, {}) if fixed_beacons else {}

                # Marcado activo: solo en experimento B
                if inject_at_eval and beacons_this_dist:
                    sample_df_eval = inject_beacons_into_sample(sample_df, beacons_this_dist)
                else:
                    sample_df_eval = sample_df

                # Discriminador
                points = sample_df_eval[["Real", "Imag"]].values
                pc = sample_point_cloud(points, POINTS_PER_SAMPLE, rng)
                x = torch.from_numpy(pc).unsqueeze(0).to(device)
                logit = disc_model(x).item()
                disc_prob = float(torch.sigmoid(torch.tensor(logit)))
                disc_flag = disc_prob < DISC_THRESHOLD

                # (solo si hay balizas)
                if beacons_this_dist:
                    v_sum = beacon_score_sum_with_fixed_beacons(sample_df_eval, beacons_this_dist, eps)
                    beacon_flag = v_sum < threshold
                else:
                    v_sum = 0
                    beacon_flag = False

                final_flag = _resolve_final_flag(disc_flag, beacon_flag, experiment_mode)

                results.append({
                    "source": source_file,
                    "target_distance": lb,
                    "distance": lb,
                    "sample_id": int(sample_id),
                    "disc_prob": disc_prob,
                    "disc_flag": int(disc_flag),
                    "v_score_sum": v_sum,
                    "threshold": threshold,
                    "beacon_flag": int(beacon_flag),
                    "final_flag": int(final_flag),
                    "experiment_mode": experiment_mode,
                })

    return pd.DataFrame(results)



def evaluate_generated_against_all_distances(
    generated_csv_path,
    threshold_by_distance,
    group_threshold,
    disc_model,
    device,
    fixed_beacons,
    experiment_mode=EXPERIMENT_MODE,
    n_per_distance=N_FAKES_PER_DISTANCE,
):
    disc_model.eval()
    results = []
    rng = np.random.default_rng(SEED)

    gen_df = pd.read_csv(generated_csv_path)
    sample_ids = sorted(gen_df["Sample_Id"].unique())

    distances = [parse_distance_from_source(f) for f in list_source_files(DATA_PATH)]

    # asignar cada fake a una distancia aleatoria
    sample_to_distance = {sid: int(rng.choice(distances)) for sid in sample_ids}

    # agrupar fakes por distancia asignada
    fakes_per_distance = {d: [] for d in distances}
    for sid, d in sample_to_distance.items():
        fakes_per_distance[d].append(sid)

    #  submuestrear n_per_distance por distancia
    selected_fakes = {}
    for d, fakes in fakes_per_distance.items():
        if len(fakes) >= n_per_distance:
            chosen = list(rng.choice(fakes, size=n_per_distance, replace=False))
        else:
            chosen = fakes
        selected_fakes[d] = chosen

    total_selected = sum(len(v) for v in selected_fakes.values())
    print(f"Selected {total_selected} fakes "
          f"(target: {len(distances)} x {n_per_distance} = {len(distances)*n_per_distance})")

    # evaluar fakes seleccionados contra su distancia asignada
    with torch.no_grad():
        for lb, sample_ids_for_lb in selected_fakes.items():
            eps, _ = epsilon_for_distance(lb)
            threshold = threshold_for_distance(lb, threshold_by_distance, group_threshold)
            beacons_this_dist = fixed_beacons.get(lb, {}) if fixed_beacons else {}

            for sample_id in sample_ids_for_lb:
                sample_df = gen_df[gen_df["Sample_Id"] == sample_id]

                points_global = sample_df[["Real", "Imag"]].values
                pc = sample_point_cloud(points_global, POINTS_PER_SAMPLE, rng)
                x = torch.from_numpy(pc).unsqueeze(0).to(device)
                logit = disc_model(x).item()
                disc_prob = float(torch.sigmoid(torch.tensor(logit)))
                disc_flag = disc_prob < DISC_THRESHOLD

                if beacons_this_dist:
                    v_sum = beacon_score_sum_with_fixed_beacons(sample_df, beacons_this_dist, eps)
                    beacon_flag = v_sum < threshold
                else:
                    v_sum = 0
                    beacon_flag = False

                #comb final
                final_flag = _resolve_final_flag(disc_flag, beacon_flag, experiment_mode)

                results.append({
                    "source": "generated.csv",
                    "target_distance": lb,
                    "distance": lb,
                    "sample_id": int(sample_id),
                    "disc_prob": disc_prob,
                    "disc_flag": int(disc_flag),
                    "v_score_sum": v_sum,
                    "threshold": threshold,
                    "beacon_flag": int(beacon_flag),
                    "final_flag": int(final_flag),
                    "experiment_mode": experiment_mode,
                })

    return pd.DataFrame(results)


# funciones guardadoo

def save_models(generator, discriminator, config_name):
    generator_path = os.path.join(MODELS_DIR, f"{MODEL_NAME}_{config_name}_generator.pt")
    discriminator_path = os.path.join(MODELS_DIR, f"{MODEL_NAME}_{config_name}_discriminator.pt")
    torch.save(generator.state_dict(), generator_path)
    torch.save(discriminator.state_dict(), discriminator_path)
    return generator_path, discriminator_path


def save_training_losses(training_losses_df, config_name):
    csv_path = os.path.join(RESULTS_DIR, f"training_losses_{MODEL_NAME}_{config_name}.csv")
    fig_path = os.path.join(FIGURES_DIR, f"training_losses_{MODEL_NAME}_{config_name}.png")
    training_losses_df.to_csv(csv_path, index=False)

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(training_losses_df["epoch"], training_losses_df["d_loss"], label="d_loss")
    ax.plot(training_losses_df["epoch"], training_losses_df["g_loss"], label="g_loss")
    ax.set_xlabel("epoch"); ax.set_ylabel("loss")
    ax.set_title(f"Training losses ({MODEL_NAME}, {config_name})")
    ax.grid(alpha=0.2); ax.legend()
    fig.tight_layout()
    fig.savefig(fig_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    return csv_path, fig_path


def save_experiment_config(config_name):
    config_data = {
        "EXPERIMENT_TYPE": EXPERIMENT_TYPE,
        "MODEL_NAME": MODEL_NAME,
        "EXPERIMENT_MODE": EXPERIMENT_MODE,
        "USE_BEACONS_IN_TRAIN": USE_BEACONS_IN_TRAIN,
        "INJECT_BEACONS_AT_EVAL": INJECT_BEACONS_AT_EVAL,
        "FI": FI, "ANGLES_DEG": ANGLES_DEG,
        "EPSILON_SHORT": EPSILON_SHORT, "EPSILON_MID": EPSILON_MID, "EPSILON_LONG": EPSILON_LONG,
        "POINTS_PER_SAMPLE": POINTS_PER_SAMPLE, "LATENT_DIM": LATENT_DIM,
        "BATCH_SIZE": BATCH_SIZE, "EPOCHS": EPOCHS,
        "LEARNING_RATE": LEARNING_RATE,
        "SEED": SEED,
        "TEST_FRACTION": TEST_FRACTION,
        "N_FAKES": N_FAKES,
        "N_FAKES_PER_DISTANCE": N_FAKES_PER_DISTANCE,
        "P_THRESHOLD": P_THRESHOLD,
        "P_DISC_THRESHOLD": P_DISC_THRESHOLD,
    }
    config_path = os.path.join(CONFIGS_DIR, f"config_{MODEL_NAME}_{config_name}.json")
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config_data, f, indent=2)
    return config_path

#entrenar pointgan
config_path = save_experiment_config(CONFIG_NAME)

# Cargar nubes reference TRAIN, marcadas con balizas fisicas
ref_points, ref_meta = build_pointclouds_from_path(
    DATA_PATH, POINTS_PER_SAMPLE, SEED,
    inject_beacons_flag=USE_BEACONS_IN_TRAIN,
    fixed_beacons_dict=fixed_beacons,
    split_dict=train_test_split,
    partition="train",
)
print(f"Reference samples loaded: {len(ref_points)}, points per sample: {ref_points.shape[1]}")
print(f"Beacons injected in training: {USE_BEACONS_IN_TRAIN}")

train_ds = PointCloudDataset(ref_points)
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
generator = PointGANGenerator(LATENT_DIM, POINTS_PER_SAMPLE).to(device)
discriminator = PointGANDiscriminator().to(device)
criterion = nn.BCEWithLogitsLoss()
g_optimizer = torch.optim.Adam(generator.parameters(), lr=LEARNING_RATE, betas=(0.5, 0.999))
d_optimizer = torch.optim.Adam(discriminator.parameters(), lr=LEARNING_RATE*1.5, betas=(0.5, 0.999))

training_losses = []
for epoch in range(1, EPOCHS + 1):
    g_loss_epoch = 0.0
    d_loss_epoch = 0.0
    for real in train_loader:
        real = real.to(device)
        batch_size = real.size(0)

        # Train discriminator
        z = torch.randn(batch_size, LATENT_DIM, device=device)
        fake = generator(z).detach()
        d_real = discriminator(real)
        d_fake = discriminator(fake)
        real_labels = torch.full_like(d_real, 0.9)
        fake_labels = torch.zeros_like(d_fake)
        loss_d = criterion(d_real, real_labels) + criterion(d_fake, fake_labels)

        d_optimizer.zero_grad()
        loss_d.backward()
        d_optimizer.step()

        # Train generator
        z = torch.randn(batch_size, LATENT_DIM, device=device)
        fake = generator(z)
        d_fake = discriminator(fake)
        loss_g = criterion(d_fake, torch.ones_like(d_fake))

        g_optimizer.zero_grad()
        loss_g.backward()
        g_optimizer.step()

        d_loss_epoch += loss_d.item()
        g_loss_epoch += loss_g.item()

    d_loss_epoch /= max(len(train_loader), 1)
    g_loss_epoch /= max(len(train_loader), 1)
    training_losses.append({
        "epoch": epoch,
        "d_loss": d_loss_epoch,
        "g_loss": g_loss_epoch,
    })
    print(f"Epoch {epoch:03d} | d_loss={d_loss_epoch:.4f} g_loss={g_loss_epoch:.4f}")

training_losses_df = pd.DataFrame(training_losses)
training_losses_csv_path, training_losses_fig_path = save_training_losses(training_losses_df, CONFIG_NAME)
models_paths = save_models(generator, discriminator, CONFIG_NAME)

save_path = os.path.join(FIGURES_DIR, f"generated_point_cloud_{CONFIG_NAME}.png")

generator.eval()
with torch.no_grad():
    z = torch.randn(1, LATENT_DIM, device=device)
    gen_points = generator(z).cpu().numpy()[0]

fig, ax = plt.subplots(figsize=(4, 4))
ax.scatter(gen_points[:, 0], gen_points[:, 1], s=5, alpha=0.6)
ax.set_title("Generated point cloud sample")
ax.set_aspect("equal", adjustable="box")
ax.grid(alpha=0.2)
fig.tight_layout()
fig.savefig(save_path, dpi=200, bbox_inches="tight")
plt.show()

print(f"Saved config: {config_path}")
print(f"Saved models: {models_paths[0]}, {models_paths[1]}")
print(f"Saved training losses CSV: {training_losses_csv_path}")
print(f"Saved training losses figure: {training_losses_fig_path}")
print(f"Saved generated sample figure: {save_path}")

# recargar modelo

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
generator = PointGANGenerator(LATENT_DIM, POINTS_PER_SAMPLE).to(device)
discriminator = PointGANDiscriminator().to(device)


# independientemente del modo de evaluacion actual
TRAINING_MODE = "disc_only" if EXPERIMENT_TYPE == "A_no_beacons" else "beacon_only"

gen_path = os.path.join(MODELS_DIR, f"{MODEL_NAME}_{TRAINING_MODE}_generator.pt")
disc_path = os.path.join(MODELS_DIR, f"{MODEL_NAME}_{TRAINING_MODE}_discriminator.pt")

generator.load_state_dict(torch.load(gen_path, map_location=device))
discriminator.load_state_dict(torch.load(disc_path, map_location=device))

generator.eval()
discriminator.eval()
print(f"Loaded generator from {gen_path}")
print(f"Loaded discriminator from {disc_path}")

#evaluacion fakes
os.makedirs(GENERATED_PATH, exist_ok=True)

centers = np.array([
    [-3,-3],[-3,-1],[-3,1],[-3,3],
    [-1,-3],[-1,-1],[-1,1],[-1,3],
    [ 1,-3],[ 1,-1],[ 1,1],[ 1,3],
    [ 3,-3],[ 3,-1],[ 3,1],[ 3,3]
])

generator.eval()
rows = []

with torch.no_grad():
    for sample_id in range(1, N_FAKES + 1):
        # Generamos muestra
        z = torch.randn(1, LATENT_DIM, device=device)
        gen = generator(z).cpu().numpy()[0]   # shape (2048, 2)
    #aplicamos mismo preprocesamiento (asignar puntos al centro mas cercano y normalizamos)
        diffs = gen[:, None, :] - centers[None, :, :]          # (2048, 16, 2)
        #dist eucl al centro
        dists = np.linalg.norm(diffs, axis=2)                  # (2048, 16)
        q_assignments = np.argmin(dists, axis=1)               # (2048,)
        assigned_centers = centers[q_assignments]              # (2048, 2)

        x_norm = gen[:, 0] - assigned_centers[:, 0]
        y_norm = gen[:, 1] - assigned_centers[:, 1]

        # Build rows for this sample
        for symbol_id in range(gen.shape[0]):
            rows.append({
                "Sample_Id": sample_id,
                "Symbol_Id": symbol_id + 1,
                "Real": gen[symbol_id, 0],
                "Imag": gen[symbol_id, 1],
                "Q": int(q_assignments[symbol_id]),
                "X_norm": x_norm[symbol_id],
                "Y_norm": y_norm[symbol_id],
            })

gen_df = pd.DataFrame(rows)
gen_csv_path = os.path.join(GENERATED_PATH, "generated.csv")
gen_df.to_csv(gen_csv_path, index=False)

print(f"Saved {N_FAKES} generated samples to {gen_csv_path}")
print(f"Total rows: {len(gen_df)}")
print(f"Sanity check - first sample shape: {len(gen_df[gen_df['Sample_Id']==1])} points")
print(f"Sanity check - Q distribution across all fakes:")
print(gen_df['Q'].value_counts().sort_index().to_string())

#eval
# Mapas de threshold
threshold_by_distance, group_threshold = build_threshold_maps(anchor_summary)

DISC_THRESHOLD = 0.5

reference_results = evaluate_reference_parallel(
    DATA_PATH,
    threshold_by_distance,
    group_threshold,
    discriminator,
    device,
    fixed_beacons,
    experiment_mode=EXPERIMENT_MODE,
    split_dict=train_test_split,
    partition="test",
    inject_at_eval=INJECT_BEACONS_AT_EVAL,
)

# Calibracion del threshold del discriminador (percentil 5 sobre reference
DISC_THRESHOLD = float(reference_results["disc_prob"].quantile(P_DISC_THRESHOLD / 100.0))
print(f"\nCalibrated DISC_THRESHOLD = {DISC_THRESHOLD:.6f}  "
      f"(percentile {P_DISC_THRESHOLD} of reference TEST disc_prob)")

# Recalcular disc_flag y final_flag en reference_results con el threshold calibrado
reference_results["disc_flag"] = (reference_results["disc_prob"] < DISC_THRESHOLD).astype(int)
if EXPERIMENT_MODE == "disc_only":
    reference_results["final_flag"] = reference_results["disc_flag"]
elif EXPERIMENT_MODE == "or":
    reference_results["final_flag"] = ((reference_results["disc_flag"] == 1) | (reference_results["beacon_flag"] == 1)).astype(int)
elif EXPERIMENT_MODE == "and":
    reference_results["final_flag"] = ((reference_results["disc_flag"] == 1) & (reference_results["beacon_flag"] == 1)).astype(int)
# beacon_only no depende del disc

generated_results = evaluate_generated_against_all_distances(
    gen_csv_path,
    threshold_by_distance,
    group_threshold,
    discriminator,
    device,
    fixed_beacons,
    experiment_mode=EXPERIMENT_MODE,
)

reference_results["distance_group"] = reference_results["distance"].apply(group_for_distance)
generated_results["distance_group"] = generated_results["distance"].apply(group_for_distance)

# metricas por distancia
metrics_per_distance = []
all_distances = sorted(set(reference_results["distance"].unique()) | set(generated_results["distance"].unique()))
for lb in all_distances:
    gen_lb = generated_results[generated_results["distance"] == lb]
    ref_lb = reference_results[reference_results["distance"] == lb]
    tp = int(gen_lb["final_flag"].sum())
    fn = int(len(gen_lb) - tp)
    fp = int(ref_lb["final_flag"].sum())
    tn = int(len(ref_lb) - fp)
    tpr = tp / (tp + fn) if (tp + fn) else 0.0
    fpr = fp / (fp + tn) if (fp + tn) else 0.0
    metrics_per_distance.append({
        "distance": lb,
        "n_fakes": len(gen_lb),
        "n_reference": len(ref_lb),
        "TP": tp, "FN": fn, "FP": fp, "TN": tn,
        "TPR": tpr, "FPR": fpr,
    })
metrics_per_distance_df = pd.DataFrame(metrics_per_distance)

# Metricas globales
tp_g = int(metrics_per_distance_df["TP"].sum())
fn_g = int(metrics_per_distance_df["FN"].sum())
fp_g = int(metrics_per_distance_df["FP"].sum())
tn_g = int(metrics_per_distance_df["TN"].sum())
tpr_g = tp_g / (tp_g + fn_g) if (tp_g + fn_g) else 0.0
fpr_g = fp_g / (fp_g + tn_g) if (fp_g + tn_g) else 0.0
precision_g = tp_g / (tp_g + fp_g) if (tp_g + fp_g) else 0.0
accuracy_g = (tp_g + tn_g) / (tp_g + tn_g + fp_g + fn_g) if (tp_g + tn_g + fp_g + fn_g) else 0.0

global_metrics = pd.DataFrame([{
    "EXPERIMENT_TYPE": EXPERIMENT_TYPE,
    "MODEL_NAME": MODEL_NAME,
    "EXPERIMENT_MODE": EXPERIMENT_MODE,
    "TP": tp_g, "FN": fn_g, "FP": fp_g, "TN": tn_g,
    "TPR": tpr_g, "FPR": fpr_g,
    "Precision": precision_g, "Accuracy": accuracy_g,
}])

# Guardado
reference_results_path = os.path.join(RESULTS_DIR, f"reference_results_{MODEL_NAME}_{CONFIG_NAME}.csv")
generated_results_path = os.path.join(RESULTS_DIR, f"generated_results_{MODEL_NAME}_{CONFIG_NAME}.csv")
metrics_per_distance_path = os.path.join(RESULTS_DIR, f"metrics_per_distance_{MODEL_NAME}_{CONFIG_NAME}.csv")
global_metrics_path = os.path.join(RESULTS_DIR, f"global_metrics_{MODEL_NAME}_{CONFIG_NAME}.csv")

reference_results.to_csv(reference_results_path, index=False)
generated_results.to_csv(generated_results_path, index=False)
metrics_per_distance_df.to_csv(metrics_per_distance_path, index=False)
global_metrics.to_csv(global_metrics_path, index=False)


display(metrics_per_distance_df.round(3))

display(global_metrics.round(3))

# histograma
fig, ax = plt.subplots(figsize=(9, 4))
ax.hist(reference_results["disc_prob"], bins=40, alpha=0.6, label="reference (test)")
gen_unique = generated_results.drop_duplicates("sample_id")
ax.hist(gen_unique["disc_prob"], bins=40, alpha=0.6, label="generated")
ax.axvline(DISC_THRESHOLD, color="red", linestyle="--", alpha=0.5, label=f"threshold={DISC_THRESHOLD:.4f}")
ax.set_title(f"disc_prob histogram ({MODEL_NAME}, {CONFIG_NAME})")
ax.set_xlabel("disc_prob"); ax.set_ylabel("count"); ax.legend()
fig.tight_layout()
disc_hist_path = os.path.join(FIGURES_DIR, f"hist_disc_prob_{MODEL_NAME}_{CONFIG_NAME}.png")
fig.savefig(disc_hist_path, dpi=200, bbox_inches="tight")
plt.show()

#  histograma de v_score
if EXPERIMENT_TYPE == "B_with_beacons":
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.hist(reference_results["v_score_sum"], bins=40, alpha=0.6, label="reference (test)")
    ax.hist(generated_results["v_score_sum"], bins=40, alpha=0.6, label="generated")
    ax.set_title(f"v_score_sum histogram ({MODEL_NAME}, {CONFIG_NAME})")
    ax.set_xlabel("v_score_sum"); ax.set_ylabel("count"); ax.legend()
    fig.tight_layout()
    v_hist_path = os.path.join(FIGURES_DIR, f"hist_v_score_sum_{MODEL_NAME}_{CONFIG_NAME}.png")
    fig.savefig(v_hist_path, dpi=200, bbox_inches="tight")
    plt.show()

print("\nSaved files:")
print(f"  {reference_results_path}")
print(f"  {generated_results_path}")
print(f"  {metrics_per_distance_path}")
print(f"  {global_metrics_path}")
print(f"  {disc_hist_path}")

# Estadisticas comparativas y curva ROC
generator.eval()
discriminator.eval()

gen_df_full = pd.read_csv(gen_csv_path)
sample_ids_all = sorted(gen_df_full["Sample_Id"].unique())

rng_eval = np.random.default_rng(SEED)
gen_disc_list = []
with torch.no_grad():
    for sample_id in sample_ids_all:
        sample_df = gen_df_full[gen_df_full["Sample_Id"] == sample_id]
        points = sample_df[["Real", "Imag"]].values
        pc = sample_point_cloud(points, POINTS_PER_SAMPLE, rng_eval)
        x = torch.from_numpy(pc).unsqueeze(0).to(device)
        logit = discriminator(x).item()
        disc_prob = float(torch.sigmoid(torch.tensor(logit)))
        gen_disc_list.append(disc_prob)

gen_disc = np.array(gen_disc_list)
ref_disc = reference_results["disc_prob"].values  # 250 reference test


mean_real = float(np.mean(ref_disc))
std_real  = float(np.std(ref_disc))
mean_gen  = float(np.mean(gen_disc))
std_gen   = float(np.std(gen_disc))


print(f"Reference (test):  mean = {mean_real:.6f}   std = {std_real:.6f}   n = {len(ref_disc)}")
print(f"Generated:         mean = {mean_gen:.6f}   std = {std_gen:.6f}   n = {len(gen_disc)}")

#  ROC y AUC (legitimas 0, sint = 1)


# El discriminador devuelve probabilidad de ser legitima -> invertimos signo
anomaly_real = 1.0 - ref_disc
anomaly_gen  = 1.0 - gen_disc

y_true  = np.concatenate([
    np.zeros_like(anomaly_real),
    np.ones_like(anomaly_gen),
])
y_score = np.concatenate([anomaly_real, anomaly_gen])

fpr, tpr, _ = roc_curve(y_true, y_score)
auc = float(roc_auc_score(y_true, y_score))

print(f"\nROC AUC = {auc:.4f}")

# Figura ROC
fig, ax = plt.subplots(figsize=(7, 6))
ax.plot(fpr, tpr, label=f"AUC = {auc:.3f}", color="tab:blue", linewidth=2)
ax.plot([0, 1], [0, 1], linestyle="--", color="gray", label="Random")
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title(f"ROC - {MODEL_NAME} ({CONFIG_NAME}) sobre test set")
ax.legend(loc="lower right")
ax.grid(True, linestyle="--", alpha=0.3)
fig.tight_layout()

roc_path = os.path.join(FIGURES_DIR, f"roc_curve_{MODEL_NAME}_{CONFIG_NAME}.png")
fig.savefig(roc_path, dpi=200, bbox_inches="tight")
plt.show()

# Histograma de disc_prob-
fig, ax = plt.subplots(figsize=(9, 4))
ax.hist(ref_disc, bins=40, alpha=0.6, label="reference (test)")
ax.hist(gen_disc, bins=40, alpha=0.6, label="generated")
ax.axvline(DISC_THRESHOLD, color="red", linestyle="--", alpha=0.5,
           label=f"threshold P5 = {DISC_THRESHOLD:.4f}")
ax.set_title(f"disc_prob histogram - 250 vs 250 ({MODEL_NAME}, {CONFIG_NAME})")
ax.set_xlabel("disc_prob"); ax.set_ylabel("count"); ax.legend()
fig.tight_layout()
hist_balanced_path = os.path.join(FIGURES_DIR, f"hist_disc_prob_balanced_{MODEL_NAME}_{CONFIG_NAME}.png")
fig.savefig(hist_balanced_path, dpi=200, bbox_inches="tight")
plt.show()

# guardar estadisticos en JSON
disc_stats = {
    "n_reference_test": int(len(ref_disc)),
    "n_generated_unique": int(len(gen_disc)),
    "mean_real": mean_real,
    "std_real": std_real,
    "mean_generated": mean_gen,
    "std_generated": std_gen,
    "threshold_p5": float(DISC_THRESHOLD),
    "roc_auc": auc,
}
stats_path = os.path.join(RESULTS_DIR, f"disc_stats_{MODEL_NAME}_{CONFIG_NAME}.json")
with open(stats_path, "w") as f:
    json.dump(disc_stats, f, indent=2)

print(f"\nSaved:")
print(f"  {roc_path}")
print(f"  {hist_balanced_path}")
print(f"  {stats_path}")

# Tabla resumen del detector de baliza
.

if EXPERIMENT_TYPE == "B_with_beacons" and INJECT_BEACONS_AT_EVAL:
    threshold_by_group = (
        anchor_summary
        .groupby("group")
        .agg(
            n_distances=("distance", "nunique"),
            threshold_min=("threshold", "min"),
            threshold_max=("threshold", "max"),
            threshold_mean=("threshold", "mean"),
            epsilon=("epsilon", "first"),
        )
        .reset_index()
    )

    beacons_by_group = (
        reference_results
        .groupby("distance_group")
        .agg(
            beacons_mean=("v_score_sum", "mean"),
            beacons_min=("v_score_sum", "min"),
            beacons_max=("v_score_sum", "max"),
        )
        .reset_index()
        .rename(columns={"distance_group": "group"})
    )

    beacon_summary_table = threshold_by_group.merge(beacons_by_group, on="group")

    # Reordenar columnas y por intervalo
    group_order = ["short", "mid", "long"]
    beacon_summary_table["group"] = pd.Categorical(
        beacon_summary_table["group"], categories=group_order, ordered=True
    )
    beacon_summary_table = beacon_summary_table.sort_values("group").reset_index(drop=True)

    beacon_summary_table = beacon_summary_table[[
        "group", "n_distances", "epsilon",
        "threshold_min", "threshold_max", "threshold_mean",
        "beacons_min", "beacons_max", "beacons_mean",
    ]]


    print(beacon_summary_table.to_string(index=False))

    out_path = os.path.join(
        RESULTS_DIR,
        f"beacon_summary_by_group_{MODEL_NAME}_{CONFIG_NAME}.csv",
    )
    beacon_summary_table.to_csv(out_path, index=False)
    print(f"\nSaved: {out_path}")
else:
    print("Solo aplica en experimento con balizas inyectadas.")

#TABLA COMPARATIVA FINAL BALIZAS
if EXPERIMENT_TYPE == "A_no_beacons":
    modes_to_check = ["disc_only"]
else:
    modes_to_check = ["beacon_only", "disc_only", "or"]

rows = []
for mode in modes_to_check:
    per_dist_path = os.path.join(
        RESULTS_DIR,
        f"metrics_per_distance_{MODEL_NAME}_{mode}.csv"
    )
    if not os.path.exists(per_dist_path):
        print(f"Skipping {mode}: file not found ({per_dist_path})")
        continue
    per_dist = pd.read_csv(per_dist_path)

    tp = int(per_dist["TP"].sum())
    fn = int(per_dist["FN"].sum())
    fp = int(per_dist["FP"].sum())
    tn = int(per_dist["TN"].sum())

    tpr = tp / (tp + fn) if (tp + fn) else 0.0
    fpr = fp / (fp + tn) if (fp + tn) else 0.0
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    accuracy = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) else 0.0

    rows.append({
        "mode": mode,
        "TP": tp, "FN": fn, "FP": fp, "TN": tn,
        "TPR": tpr, "FPR": fpr,
        "Precision": precision, "Accuracy": accuracy,
    })

master_table = pd.DataFrame(rows)
master_path = os.path.join(RESULTS_DIR, f"master_summary_{MODEL_NAME}.csv")
master_table.to_csv(master_path, index=False)

print(f"=== Master comparison table ({MODEL_NAME}) ===")
display(master_table.round(3))
print(f"\nSaved to: {master_path}")

# Eliminación de balizas de una muestra
def remove_beacons_from_sample(sample_df, beacons_per_cluster, eps):

    if not beacons_per_cluster:
        return sample_df.copy(), 0

    rows_to_drop = []

    for q, beacon_positions in beacons_per_cluster.items():
        cluster_mask = sample_df["Q"] == q
        cluster_df = sample_df[cluster_mask]
        if cluster_df.empty:
            continue

        # Coordenadas normalizadas de los puntos del q
        points = cluster_df[["X_norm", "Y_norm"]].values  #

        # Calcular dist de cada punto a cualquier baliza esperada
        diffs = points[:, None, :] - beacon_positions[None, :, :]
        dists = np.linalg.norm(diffs, axis=2)  # (N_points, N_beacons)
        min_dist_per_point = dists.min(axis=1)  # (N_points,)

        # eliminar
        is_beacon_point = min_dist_per_point < eps
        rows_to_drop.extend(cluster_df.index[is_beacon_point].tolist())

    n_removed = len(rows_to_drop)
    clean_df = sample_df.drop(index=rows_to_drop).reset_index(drop=True)
    return clean_df, n_removed

test_distance = sorted(fixed_beacons.keys())[0]  # primera distancia disponible
test_sample_id = train_test_split[test_distance]["test"][0]
source_file = f"source_{test_distance}.csv"
df = pd.read_csv(os.path.join(DATA_PATH, source_file))
sample_df = df[df["Sample_Id"] == test_sample_id]


beacons_this_dist = fixed_beacons[test_distance]
sample_marked = inject_beacons_into_sample(sample_df, beacons_this_dist)

eps, _ = epsilon_for_distance(test_distance)
sample_clean, n_removed = remove_beacons_from_sample(sample_marked, beacons_this_dist, eps)

print(f"Distancia {test_distance}, Sample {test_sample_id}")
print(f"  Puntos antes de marcar: {len(sample_df)}")
print(f"  Puntos tras marcar:     {len(sample_marked)}")
print(f"  Puntos tras limpiar:    {len(sample_clean)}")
print(f"  Balizas eliminadas:     {n_removed}")
print(f"  Esperado: balizas eliminadas = 64 y limpieza = original")
print(f"  ✓ Test pasa: {n_removed == 64 and len(sample_clean) == len(sample_df)}")
