# -*- coding: utf-8 -*-
"""Gan_convencional_git.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ONttewh3WjMSLx0zAP_ZuAuzO73uDAu
"""

import numpy as np
import matplotlib.pyplot as plt
import sys
import os
import torch
import pandas as pd
import random
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
import json
from scipy.ndimage import gaussian_filter
from keras.models import Sequential
from keras.layers import Dense, Activation, LeakyReLU
from keras.optimizers import Adam
from torch.utils.data import Dataset
from keras import backend as K
from sklearn.metrics import precision_recall_curve, roc_curve, roc_auc_score, f1_score, precision_score, recall_score

from google.colab import drive
drive.mount('/content/drive')

# Configuracion de salida

SEED = 42
np.random.seed(SEED)
random.seed(SEED)
tf.random.set_seed(SEED)

DRIVE_BASE  = "/content/drive/MyDrive/TFG"
RESULTS_DIR = os.path.join(DRIVE_BASE, "results", "model1_gan_cluster0")
FIGURES_DIR = os.path.join(RESULTS_DIR, "figures")
MODELS_DIR  = os.path.join(RESULTS_DIR, "models")

os.makedirs(FIGURES_DIR, exist_ok=True)
os.makedirs(MODELS_DIR,  exist_ok=True)

print("Resultados se guardaran en:", RESULTS_DIR)

def create_histogram(
    x,
    y,
    resolution=64,
    value_range=(-1,1)
):
#crear imagen
    H, _, _ = np.histogram2d(
        x,
        y,
        bins=resolution,
        range=[
            [value_range[0], value_range[1]],
            [value_range[0], value_range[1]]
        ]
    )
#Normalización
    if H.max() > 0:
        H = H / H.max()
#Ajuste a [-1,1] para tanh de GAN
    H = H * 2 - 1

    return H

class ClusterDataset(Dataset):
    def __init__(self, files, folder, q, resolution):
#Leemos CSV, extraemos puntos IQ, convertimos a histograma y creamos Dataset para GAN
        self.data = []

        for file in files:

            path = os.path.join(folder, file)
            df = pd.read_csv(path)

            for sample_id in df["Sample_Id"].unique():

                df_sample = df[df["Sample_Id"] == sample_id]
                cluster = df_sample[df_sample["Q"] == q]

                x = cluster["X_norm"].values
                y = cluster["Y_norm"].values

                if len(x) < 10: #per clusters que tenen pocs punts
                  continue

                H = create_histogram(
                    x,
                    y,
                    resolution
                )
                self.data.append(H)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img = torch.tensor(self.data[idx], dtype=torch.float32).unsqueeze(0)
        return img

data_ref_path = "/content/drive/MyDrive/TFG/data_processed/reference_clusters"
files_ref = sorted(os.listdir(data_ref_path))

print("Numero de archivos:", len(files_ref))

q = 0                # cluster a analizar
resolution = 96

dataset = ClusterDataset(files_ref, data_ref_path, q, resolution=resolution)

def load_data(dataset):
    data = []
    for i in range(len(dataset)):
        img = dataset[i][0].numpy()
        img = img.squeeze()
        data.append(img)
    return np.array(data)

X_train = load_data(dataset)

print("Dataset shape:", X_train.shape)

#imagenes 64x64 a vectores de resolution*resolution
def preprocess(x):
    x = x.reshape(-1, resolution*resolution)
    x = np.float64(x)
    return x

X_train_real = preprocess(X_train)
print(X_train_real.shape)

def make_latent_samples(n_samples, sample_size):
    return np.random.normal(loc=0, scale=1, size=(n_samples, sample_size))

def make_labels(size):
    return np.ones([size, 1]), np.zeros([size, 1])

def make_trainable(model, trainable):
    for layer in model.layers:
        layer.trainable = trainable

def histogram_to_iq_points(
    hist,
    num_points=128,
    value_range=(-1, 1)
):
    # puntos IQ a partir de un histograma 2D normalizado en [-1,1].


    if len(hist.shape) == 3:
        hist = hist.squeeze()

    # [-1,1] -> [0,1]
    hist = (hist + 1) / 2
    hist = np.clip(hist, 0, None)

    # Normalizar como distribucion de probabilidad
    prob = hist / np.sum(hist)
    resolution = hist.shape[0]
    flat_prob = prob.flatten()

    # Sampling probabilistico
    sampled_idx = np.random.choice(
        len(flat_prob),
        size=num_points,
        p=flat_prob
    )
    rows, cols = np.unravel_index(sampled_idx, (resolution, resolution))

    # Pixeles -> coordenadas IQ + jitter sub-pixel
    min_val, max_val = value_range
    x = min_val + (cols / resolution) * (max_val - min_val)
    y = min_val + (rows / resolution) * (max_val - min_val)
    pixel_size = (max_val - min_val) / resolution
    x += np.random.uniform(-pixel_size/2, pixel_size/2, size=num_points)
    y += np.random.uniform(-pixel_size/2, pixel_size/2, size=num_points)

    return x, y

#Convierte un vector de puntos IQ a histograma 2D normalizado en [-1,1]
def iq_to_histogram(x, y, resolution=96, value_range=(-1, 1)):
    return create_histogram(x, y, resolution, value_range)

def make_simple_GAN(sample_size,
                    g_hidden_size,
                    d_hidden_size,
                    leaky_alpha,
                    g_learning_rate,
                    d_learning_rate):
    K.clear_session()

    generator = Sequential([
        Dense(g_hidden_size, input_shape=(sample_size,)),
        LeakyReLU(alpha=leaky_alpha),
        Dense(resolution*resolution),
        Activation('tanh')
    ], name='generator')

    discriminator = Sequential([
        Dense(d_hidden_size, input_shape=(resolution*resolution,)),
        LeakyReLU(alpha=leaky_alpha),
        Dense(1),
        Activation('sigmoid')
    ], name='discriminator')

    gan = Sequential([
        generator,
        discriminator
    ])

    discriminator.compile(optimizer=Adam(learning_rate=d_learning_rate,beta_1=0.5), loss='binary_crossentropy')
    gan.compile(optimizer=Adam(learning_rate=g_learning_rate,beta_1=0.5), loss='binary_crossentropy')

    return gan, generator, discriminator

#visualitzar valors (estem agafant nomes q = 0)
print("Shape X_train:", X_train.shape)
print("Min:", X_train.min())
print("Max:", X_train.max())

# hiperparametros
sample_size     = 100
g_hidden_size   = 256
d_hidden_size   = 256
leaky_alpha     = 0.2
g_learning_rate = 0.0002  # learning rate generador
d_learning_rate = 0.0002  # learning rate discriminador
epochs          = 500
batch_size      = 64
eval_size       = 16      # evaluate size
smooth          = 0.1

#etiquetas
y_train_real, y_train_fake = make_labels(batch_size)
y_eval_real,  y_eval_fake  = make_labels(eval_size)

#crear GAN como en tutorial
gan, generator, discriminator = make_simple_GAN(
    sample_size,
    g_hidden_size,
    d_hidden_size,
    leaky_alpha,
    g_learning_rate,
    d_learning_rate)

losses = []
for e in range(epochs):
    for i in range(len(X_train_real)//batch_size):

        X_batch_real = X_train_real[i*batch_size:(i+1)*batch_size]

        # generr imagenes
        latent_samples = make_latent_samples(batch_size, sample_size)
        X_batch_fake = generator.predict_on_batch(latent_samples)

        # entrenar al discriminador
        make_trainable(discriminator, True)
        discriminator.train_on_batch(X_batch_real, y_train_real * (1 - smooth))
        discriminator.train_on_batch(X_batch_fake, y_train_fake)

        # entrenar al generador via GAN
        make_trainable(discriminator, False)
        gan.train_on_batch(latent_samples, y_train_real)

    # ectualizacion de pesos
    X_eval_real = X_train_real[np.random.choice(len(X_train_real), eval_size, replace=False)]
    latent_samples = make_latent_samples(eval_size, sample_size)
    X_eval_fake = generator.predict_on_batch(latent_samples)

    d_loss  = discriminator.test_on_batch(X_eval_real, y_eval_real)
    d_loss += discriminator.test_on_batch(X_eval_fake, y_eval_fake)
    g_loss  = gan.test_on_batch(latent_samples, y_eval_real)

    losses.append((d_loss, g_loss))

    print("Epoch: {:>3}/{} Discriminator Loss: {:>6.4f} Generator Loss: {:>6.4f}".format(
        e+1, epochs, d_loss, g_loss))

generator.save(os.path.join(MODELS_DIR, "generator.keras"))
discriminator.save(os.path.join(MODELS_DIR, "discriminator.keras"))
np.save(os.path.join(RESULTS_DIR, "training_losses.npy"), np.array(losses))
print("Modelos guardados en:", MODELS_DIR)

losses = np.array(losses)

fig, ax = plt.subplots()
plt.plot(losses.T[0], label='Discriminator')
plt.plot(losses.T[1], label='Generator')
plt.title("Training Losses")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.savefig(os.path.join(FIGURES_DIR, "training_losses.png"), dpi=150, bbox_inches="tight")
plt.show()

def deprocess(x):
    x = (x + 1) / 2.0 * 255.0
    x = np.clip(x, 0, 255)
    x = np.uint8(x)
    x = x.reshape(resolution, resolution)
    return x

def get_scores(discriminator, X):
    return discriminator.predict(X).flatten()

# EVALUACION
#puntuacion en legitimas
scores_real = get_scores(discriminator, X_train_real)

# Generar muestras sinteticas con el generador entrenado
n_gen = len(X_train_real)  # mismo numero que reference para equilibrar clases
latent_eval = make_latent_samples(n_gen, sample_size)
X_generated = generator.predict(latent_eval, verbose=0)
scores_generated = get_scores(discriminator, X_generated)

# Thresholds calibrados solo con muestras legitimas
threshold_perc = np.percentile(scores_real, 5)
mu = np.mean(scores_real)
sigma = np.std(scores_real)
threshold_stat = mu - 3 * sigma

print(f"Threshold (percentil 5):  {threshold_perc:.4f}")
print(f"Threshold (mu - 3 sigma): {threshold_stat:.4f}")
print(f"Score medio reference:    {mu:.4f}")
print(f"Score medio generated:    {np.mean(scores_generated):.4f}")

#  Tasas de deteccion sobre las muestras generadas
# El discriminador devuelve probabilidad de ser real : puntuacion < umbral --> anomalo

det_stat = np.mean(scores_generated < threshold_stat)
det_perc = np.mean(scores_generated < threshold_perc)

print(f"Detection rate (mu - 3 sigma):  {det_stat:.4f}")
print(f"Detection rate (percentil 5):   {det_perc:.4f}")

plt.figure()
plt.hist(scores_real,      bins=50, alpha=0.5, label='Reference (legitimas)')
plt.hist(scores_generated, bins=50, alpha=0.5, label='Generated (sinteticas)')
plt.axvline(threshold_stat, color='green', linestyle='--', linewidth=2, label='mu - 3 sigma')
plt.axvline(threshold_perc, color='red',   linestyle='--', linewidth=2, label='Percentil 5%')
plt.xlabel('Score del discriminador')
plt.ylabel('Frecuencia')
plt.title('Distribucion de scores: reference vs generated')
plt.legend()
plt.savefig(os.path.join(FIGURES_DIR, "score_distribution.png"), dpi=150, bbox_inches="tight")
plt.show()

# Metricas y curvas para deteccion de anomalias: reference (0) vs sinteticas (1)
y_true = np.concatenate([
    np.zeros_like(scores_real),       # 0 = legitima
    np.ones_like(scores_generated),   # 1 = anomala (sintetica)
])

# Anomaly score: cuanto mayor, mas anomalo. El discriminador devuelve probabilidad de ser real (se invierte)
y_score = np.concatenate([
    1.0 - scores_real,
    1.0 - scores_generated,
])

# ROC
fpr, tpr, roc_thresholds = roc_curve(y_true, y_score)
roc_auc = roc_auc_score(y_true, y_score)

precision, recall, pr_thresholds = precision_recall_curve(y_true, y_score)

f1_vals = (2 * precision[:-1] * recall[:-1]) / (precision[:-1] + recall[:-1] + 1e-12)
best_idx = int(np.argmax(f1_vals))
best_threshold = pr_thresholds[best_idx]

# Conversion de thresholds del discriminador a la escala de anomalia
anomaly_threshold_perc = 1.0 - threshold_perc
anomaly_threshold_stat = 1.0 - threshold_stat

def compute_metrics_at_threshold(threshold):
    y_pred = (y_score >= threshold).astype(int)
    return {
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall":    recall_score(y_true, y_pred, zero_division=0),
        "f1":        f1_score(y_true, y_pred, zero_division=0),
    }

metrics_perc = compute_metrics_at_threshold(anomaly_threshold_perc)
metrics_stat = compute_metrics_at_threshold(anomaly_threshold_stat)
metrics_best = compute_metrics_at_threshold(best_threshold)

print("ROC AUC:", round(roc_auc, 4))
print("Best F1 threshold (en escala de anomalia):", round(best_threshold, 4))
print("Metricas @ threshold percentil 5: ", metrics_perc)
print("Metricas @ threshold mu - 3 sigma:", metrics_stat)
print("Metricas @ best F1:               ", metrics_best)

fig, ax = plt.subplots(1, 2, figsize=(12, 5))

ax[0].plot(fpr, tpr, label=f"ROC AUC = {roc_auc:.3f}")
ax[0].plot([0, 1], [0, 1], linestyle="--", color="gray")
ax[0].set_xlabel("False Positive Rate")
ax[0].set_ylabel("True Positive Rate")
ax[0].set_title("Curva ROC (reference vs generated)")
ax[0].legend()

ax[1].plot(recall, precision, label="PR curve")
ax[1].set_xlabel("Recall")
ax[1].set_ylabel("Precision")
ax[1].set_title("Curva Precision-Recall (reference vs generated)")
ax[1].legend()

plt.tight_layout()
plt.savefig(os.path.join(FIGURES_DIR, "roc_pr_curves.png"), dpi=150, bbox_inches="tight")
plt.show()

# Recargar los modelos entrenados
generator = keras.models.load_model(os.path.join(MODELS_DIR, "generator.keras"))
discriminator = keras.models.load_model(os.path.join(MODELS_DIR, "discriminator.keras"))


print("Modelos 'generator' y 'discriminator' cargados exitosamente.")
print(f"sample_size: {sample_size}")
print(f"resolution: {resolution}")

results = {
    "model":        "GAN convencional (MLP, q=0, prototipo per-cluster)",
    "seed":         SEED,
    "resolution":   int(resolution),
    "cluster_q":    int(q),
    "epochs":       int(epochs),
    "batch_size":   int(batch_size),
    "latent_dim":   int(sample_size),
    "n_reference":  int(len(scores_real)),
    "n_generated":  int(len(scores_generated)),
    "thresholds": {
        "percentil_5":             float(threshold_perc),
        "mu_minus_3sigma":         float(threshold_stat),
        "best_f1_anomaly_scale":   float(best_threshold),
    },
    "score_stats": {
        "reference": {
            "mean": float(np.mean(scores_real)),
            "std":  float(np.std(scores_real)),
            "min":  float(np.min(scores_real)),
            "max":  float(np.max(scores_real)),
        },
        "generated": {
            "mean": float(np.mean(scores_generated)),
            "std":  float(np.std(scores_generated)),
            "min":  float(np.min(scores_generated)),
            "max":  float(np.max(scores_generated)),
        },
    },
    "detection_rates": {
        "percentil_5":     float(det_perc),
        "mu_minus_3sigma": float(det_stat),
    },
    "roc_auc":          float(roc_auc),
    "metrics_percentil_5":      {k: float(v) for k, v in metrics_perc.items()},
    "metrics_mu_minus_3sigma":  {k: float(v) for k, v in metrics_stat.items()},
    "metrics_best_f1":          {k: float(v) for k, v in metrics_best.items()},
}

summary_path = os.path.join(RESULTS_DIR, "results_summary.json")
with open(summary_path, "w") as f:
    json.dump(results, f, indent=2)

# guardamos puntuaciones por si hay que rehacer plots
np.savez(
    os.path.join(RESULTS_DIR, "scores.npz"),
    scores_real=scores_real,
    scores_generated=scores_generated,
    fpr=fpr,
    tpr=tpr,
    precision=precision,
    recall=recall,
)

print("Resumen guardado en:", summary_path)
print(json.dumps(results, indent=2))